// Class: ReadkMLP_pca_ce_600_(n-2)2_no_ev
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::kMLP_pca_ce_600_(n-2)2_no_ev
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/34       [336418]
Creator        : knowakow
Date           : Fri Jun  7 20:28:15 2019
Host           : Linux lxbuild05 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux
Dir            : /lustre/nyx/hades/user/knowakow/PNB/FAT/TMVA
Training events: 1000000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N-2,N-2" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N,P" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
CalculateErrors: "True" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 17
dist_p_pim                    dist_p_pim                    dist_p_pim                    dist_p_pim                    mm                                'F'    [8.06744174042e-06,492.172912598]
dist_pip_pim                  dist_pip_pim                  dist_pip_pim                  dist_pip_pim                  mm                                'F'    [1.23587478811e-05,528.975280762]
eVert_x                       eVert_x                       eVert_x                       eVert_x                       mm                                'F'    [-6712.00195312,421.311126709]
eVert_y                       eVert_y                       eVert_y                       eVert_y                       mm                                'F'    [-4322.33398438,557.776550293]
eVert_z                       eVert_z                       eVert_z                       eVert_z                       mm                                'F'    [-372.324371338,7005.60400391]
ver_pip_pim_x                 ver_pip_pim_x                 ver_pip_pim_x                 ver_pip_pim_x                 mm                                'F'    [-7900.82275391,7244.55957031]
ver_pip_pim_y                 ver_pip_pim_y                 ver_pip_pim_y                 ver_pip_pim_y                 mm                                'F'    [-3637.93334961,10262.6113281]
ver_pip_pim_z                 ver_pip_pim_z                 ver_pip_pim_z                 ver_pip_pim_z                 mm                                'F'    [-16211.0849609,3770.25610352]
ver_p_pim_x                   ver_p_pim_x                   ver_p_pim_x                   ver_p_pim_x                   mm                                'F'    [-38084.8515625,6029.96435547]
ver_p_pim_y                   ver_p_pim_y                   ver_p_pim_y                   ver_p_pim_y                   mm                                'F'    [-94022.8125,8030.11816406]
ver_p_pim_z                   ver_p_pim_z                   ver_p_pim_z                   ver_p_pim_z                   mm                                'F'    [-44827.8710938,7534.72558594]
oa_lambda                     oa_lambda                     oa_lambda                     oa_lambda                     deg                               'F'    [0.0220243129879,179.991531372]
dist_p_eVert                  dist_p_eVert                  dist_p_eVert                  dist_p_eVert                  mm                                'F'    [0.00406167190522,5657.98974609]
dist_pim_eVert                dist_pim_eVert                dist_pim_eVert                dist_pim_eVert                mm                                'F'    [0.00498456507921,7820.19091797]
dist_lambda_eVert             dist_lambda_eVert             dist_lambda_eVert             dist_lambda_eVert             mm                                'F'    [0.00600005546585,6695.12744141]
dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       dist_lambda_ver_pip_pim       mm                                'F'    [0.00836985651404,18368.9785156]
dist_ver_to_ver               dist_ver_to_ver               dist_ver_to_ver               dist_ver_to_ver               mm                                'F'    [0.0658141672611,110893.085938]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadkMLP_pca_ce_600_(n-2)2_no_ev : public IClassifierReader {

 public:

   // constructor
   ReadkMLP_pca_ce_600_(n-2)2_no_ev( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadkMLP_pca_ce_600_(n-2)2_no_ev" ),
        fNvars( 17 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dist_p_pim", "dist_pip_pim", "eVert_x", "eVert_y", "eVert_z", "ver_pip_pim_x", "ver_pip_pim_y", "ver_pip_pim_z", "ver_p_pim_x", "ver_p_pim_y", "ver_p_pim_z", "oa_lambda", "dist_p_eVert", "dist_pim_eVert", "dist_lambda_eVert", "dist_lambda_ver_pip_pim", "dist_ver_to_ver" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1.01002061367035;
      fVmax[0] = 0.991412997245789;
      fVmin[1] = -0.0351707711815834;
      fVmax[1] = 1.97063207626343;
      fVmin[2] = -0.0749979540705681;
      fVmax[2] = 1.97431409358978;
      fVmin[3] = -0.142972469329834;
      fVmax[3] = 4.51759147644043;
      fVmin[4] = -1.97954022884369;
      fVmax[4] = 0.0495334677398205;
      fVmin[5] = -1.06617152690887;
      fVmax[5] = 2.27725005149841;
      fVmin[6] = -0.54257869720459;
      fVmax[6] = 2.79834866523743;
      fVmin[7] = -1.19429397583008;
      fVmax[7] = 1.70348238945007;
      fVmin[8] = -0.563660204410553;
      fVmax[8] = 0.216474294662476;
      fVmin[9] = -0.493345499038696;
      fVmax[9] = 0.65705794095993;
      fVmin[10] = -0.506779611110687;
      fVmax[10] = 0.401258140802383;
      fVmin[11] = -0.199167758226395;
      fVmax[11] = 0.406484425067902;
      fVmin[12] = -0.10093031078577;
      fVmax[12] = 0.0838776901364326;
      fVmin[13] = -0.440606415271759;
      fVmax[13] = 0.333481103181839;
      fVmin[14] = -0.164238110184669;
      fVmax[14] = 0.0557983964681625;
      fVmin[15] = -0.0964990109205246;
      fVmax[15] = 0.0645397454500198;
      fVmin[16] = -0.207746371626854;
      fVmax[16] = 0.0177918486297131;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadkMLP_pca_ce_600_(n-2)2_no_ev() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][17];
   double fMax_1[3][17];

   void X2P_2( const double*, double*, int ) const;
   double fMeanValues_2[3][17];
   double fEigenVectors_2[3][17][17];

   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform_2();
   void Transform_2( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[17];
   double fVmax[17];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[17];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[16][18];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[16][16];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][16];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadkMLP_pca_ce_600_(n-2)2_no_ev::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 18; fWeights[0] = new double[18]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 16; fWeights[2] = new double[16]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.341176853524219;
   fWeightMatrix0to1[1][0] = -0.150524079352262;
   fWeightMatrix0to1[2][0] = 0.182132560303034;
   fWeightMatrix0to1[3][0] = 6.33117412812875;
   fWeightMatrix0to1[4][0] = -7.55390083183186;
   fWeightMatrix0to1[5][0] = -0.576574893250192;
   fWeightMatrix0to1[6][0] = -0.288712812860188;
   fWeightMatrix0to1[7][0] = 1.14308051822473;
   fWeightMatrix0to1[8][0] = -1.60838346426695;
   fWeightMatrix0to1[9][0] = -0.356753053519593;
   fWeightMatrix0to1[10][0] = 0.459842737806927;
   fWeightMatrix0to1[11][0] = -0.324190881021349;
   fWeightMatrix0to1[12][0] = -0.635956162314727;
   fWeightMatrix0to1[13][0] = 4.31001380356592;
   fWeightMatrix0to1[14][0] = -0.388068853565212;
   fWeightMatrix0to1[0][1] = 7.88868222374212;
   fWeightMatrix0to1[1][1] = -4.20455257203823;
   fWeightMatrix0to1[2][1] = 4.02964035906484;
   fWeightMatrix0to1[3][1] = -0.920669736165047;
   fWeightMatrix0to1[4][1] = 6.90146296140894;
   fWeightMatrix0to1[5][1] = 0.350056735375453;
   fWeightMatrix0to1[6][1] = -3.00658032475272;
   fWeightMatrix0to1[7][1] = -0.511057142908985;
   fWeightMatrix0to1[8][1] = 1.25298928380125;
   fWeightMatrix0to1[9][1] = -6.83302878720528;
   fWeightMatrix0to1[10][1] = 10.3896480605958;
   fWeightMatrix0to1[11][1] = 9.39902257371405;
   fWeightMatrix0to1[12][1] = 1.33490397993402;
   fWeightMatrix0to1[13][1] = -7.36142360789535;
   fWeightMatrix0to1[14][1] = 10.9854592751658;
   fWeightMatrix0to1[0][2] = 1.22835225963971;
   fWeightMatrix0to1[1][2] = 2.04765413514557;
   fWeightMatrix0to1[2][2] = -3.31691219577476;
   fWeightMatrix0to1[3][2] = 0.833501612179506;
   fWeightMatrix0to1[4][2] = 3.71068640294844;
   fWeightMatrix0to1[5][2] = -0.49131295737836;
   fWeightMatrix0to1[6][2] = -7.43826550254134;
   fWeightMatrix0to1[7][2] = 2.04987698752522;
   fWeightMatrix0to1[8][2] = -0.325203094579432;
   fWeightMatrix0to1[9][2] = 6.37510819707252;
   fWeightMatrix0to1[10][2] = 4.36706943098382;
   fWeightMatrix0to1[11][2] = 5.17320398643188;
   fWeightMatrix0to1[12][2] = 3.86265467480718;
   fWeightMatrix0to1[13][2] = 1.55474039448898;
   fWeightMatrix0to1[14][2] = -0.539113077345344;
   fWeightMatrix0to1[0][3] = -7.24740671997306;
   fWeightMatrix0to1[1][3] = 31.7164053358588;
   fWeightMatrix0to1[2][3] = 2.0662984712989;
   fWeightMatrix0to1[3][3] = 18.0427745732952;
   fWeightMatrix0to1[4][3] = 3.07249483068864;
   fWeightMatrix0to1[5][3] = 0.988447725534878;
   fWeightMatrix0to1[6][3] = -16.0132957068934;
   fWeightMatrix0to1[7][3] = 0.200663614892569;
   fWeightMatrix0to1[8][3] = 1.49283467726781;
   fWeightMatrix0to1[9][3] = -20.8735723291299;
   fWeightMatrix0to1[10][3] = 2.3053426160264;
   fWeightMatrix0to1[11][3] = 6.94251293174476;
   fWeightMatrix0to1[12][3] = -0.629206448577731;
   fWeightMatrix0to1[13][3] = -9.80598408700691;
   fWeightMatrix0to1[14][3] = 3.37642201759223;
   fWeightMatrix0to1[0][4] = -0.155198996990671;
   fWeightMatrix0to1[1][4] = -20.3759180980049;
   fWeightMatrix0to1[2][4] = -2.39800047388522;
   fWeightMatrix0to1[3][4] = -5.54814214354693;
   fWeightMatrix0to1[4][4] = -2.48404169665568;
   fWeightMatrix0to1[5][4] = -0.420163609407436;
   fWeightMatrix0to1[6][4] = 15.1312108850261;
   fWeightMatrix0to1[7][4] = -2.16408348411116;
   fWeightMatrix0to1[8][4] = -0.0601634125575472;
   fWeightMatrix0to1[9][4] = 14.4549770720791;
   fWeightMatrix0to1[10][4] = -6.7150562495159;
   fWeightMatrix0to1[11][4] = -12.4376461354596;
   fWeightMatrix0to1[12][4] = -0.956085697228345;
   fWeightMatrix0to1[13][4] = 8.46781901910169;
   fWeightMatrix0to1[14][4] = -3.20442811454523;
   fWeightMatrix0to1[0][5] = -1.71204641777982;
   fWeightMatrix0to1[1][5] = 4.57443403862215;
   fWeightMatrix0to1[2][5] = -1.39721582377312;
   fWeightMatrix0to1[3][5] = 3.02032770759325;
   fWeightMatrix0to1[4][5] = 2.38807973487777;
   fWeightMatrix0to1[5][5] = 1.8309337124759;
   fWeightMatrix0to1[6][5] = -3.26040922933729;
   fWeightMatrix0to1[7][5] = 1.2139472971301;
   fWeightMatrix0to1[8][5] = -0.749074234609033;
   fWeightMatrix0to1[9][5] = -4.65080562070714;
   fWeightMatrix0to1[10][5] = 0.542345541579612;
   fWeightMatrix0to1[11][5] = 2.85377502349422;
   fWeightMatrix0to1[12][5] = -0.563220298060762;
   fWeightMatrix0to1[13][5] = -3.15380093588764;
   fWeightMatrix0to1[14][5] = -1.12663469957993;
   fWeightMatrix0to1[0][6] = 2.13988494377432;
   fWeightMatrix0to1[1][6] = -9.48673388597977;
   fWeightMatrix0to1[2][6] = 1.58870708725884;
   fWeightMatrix0to1[3][6] = -5.65693220259624;
   fWeightMatrix0to1[4][6] = -2.0896712911934;
   fWeightMatrix0to1[5][6] = 1.86657995977707;
   fWeightMatrix0to1[6][6] = 4.29266691892056;
   fWeightMatrix0to1[7][6] = -2.06989527228275;
   fWeightMatrix0to1[8][6] = -1.46212269838576;
   fWeightMatrix0to1[9][6] = 5.0042541331441;
   fWeightMatrix0to1[10][6] = -2.45955454933652;
   fWeightMatrix0to1[11][6] = -3.23175804180302;
   fWeightMatrix0to1[12][6] = 0.261607038823545;
   fWeightMatrix0to1[13][6] = 4.05774825328952;
   fWeightMatrix0to1[14][6] = -1.33948241515523;
   fWeightMatrix0to1[0][7] = 2.21862637092016;
   fWeightMatrix0to1[1][7] = 2.04696866142275;
   fWeightMatrix0to1[2][7] = -0.381296730626775;
   fWeightMatrix0to1[3][7] = 0.570388533858521;
   fWeightMatrix0to1[4][7] = 1.49012776788814;
   fWeightMatrix0to1[5][7] = -1.6715071370184;
   fWeightMatrix0to1[6][7] = -3.31710495748957;
   fWeightMatrix0to1[7][7] = 0.433605085934906;
   fWeightMatrix0to1[8][7] = 0.906977765836081;
   fWeightMatrix0to1[9][7] = -4.77999573721595;
   fWeightMatrix0to1[10][7] = 4.32375636080602;
   fWeightMatrix0to1[11][7] = 4.43977605550384;
   fWeightMatrix0to1[12][7] = -0.583409715952672;
   fWeightMatrix0to1[13][7] = -0.745443836330057;
   fWeightMatrix0to1[14][7] = 0.425083952073592;
   fWeightMatrix0to1[0][8] = -3.5295196848684;
   fWeightMatrix0to1[1][8] = 13.5087605019642;
   fWeightMatrix0to1[2][8] = 0.607213455612669;
   fWeightMatrix0to1[3][8] = 8.01035147564917;
   fWeightMatrix0to1[4][8] = 1.56958691466648;
   fWeightMatrix0to1[5][8] = -0.332055939128234;
   fWeightMatrix0to1[6][8] = -7.82400509056387;
   fWeightMatrix0to1[7][8] = 1.02915667508238;
   fWeightMatrix0to1[8][8] = -1.7879380600272;
   fWeightMatrix0to1[9][8] = -7.38986419557334;
   fWeightMatrix0to1[10][8] = 1.67699765799309;
   fWeightMatrix0to1[11][8] = 1.74788401732148;
   fWeightMatrix0to1[12][8] = 1.16488842646406;
   fWeightMatrix0to1[13][8] = -6.41506817037214;
   fWeightMatrix0to1[14][8] = 1.65975091425916;
   fWeightMatrix0to1[0][9] = 1.1153600479127;
   fWeightMatrix0to1[1][9] = -1.3228788881138;
   fWeightMatrix0to1[2][9] = -2.16449669968631;
   fWeightMatrix0to1[3][9] = -0.109363464144865;
   fWeightMatrix0to1[4][9] = -0.220176779040208;
   fWeightMatrix0to1[5][9] = 1.46807122797436;
   fWeightMatrix0to1[6][9] = 3.7216880777214;
   fWeightMatrix0to1[7][9] = -1.59267809492573;
   fWeightMatrix0to1[8][9] = -0.705781056762939;
   fWeightMatrix0to1[9][9] = 1.77502510493904;
   fWeightMatrix0to1[10][9] = -0.407035008191238;
   fWeightMatrix0to1[11][9] = -2.59383523644067;
   fWeightMatrix0to1[12][9] = -1.03471174389076;
   fWeightMatrix0to1[13][9] = 0.485754262771767;
   fWeightMatrix0to1[14][9] = -0.969841883751375;
   fWeightMatrix0to1[0][10] = -0.921550221583399;
   fWeightMatrix0to1[1][10] = 4.11291308475887;
   fWeightMatrix0to1[2][10] = 2.3964251544638;
   fWeightMatrix0to1[3][10] = 0.424268850103642;
   fWeightMatrix0to1[4][10] = 0.83154439711083;
   fWeightMatrix0to1[5][10] = 0.395334092879865;
   fWeightMatrix0to1[6][10] = -2.5806415672482;
   fWeightMatrix0to1[7][10] = 0.730312798501658;
   fWeightMatrix0to1[8][10] = 1.34613454700533;
   fWeightMatrix0to1[9][10] = -5.37511484361044;
   fWeightMatrix0to1[10][10] = 3.75952596440125;
   fWeightMatrix0to1[11][10] = 4.35768934556006;
   fWeightMatrix0to1[12][10] = 1.05123448926902;
   fWeightMatrix0to1[13][10] = -1.08350252674648;
   fWeightMatrix0to1[14][10] = 2.67755830480853;
   fWeightMatrix0to1[0][11] = -2.2605946835976;
   fWeightMatrix0to1[1][11] = 8.05203474634869;
   fWeightMatrix0to1[2][11] = 1.06931911244628;
   fWeightMatrix0to1[3][11] = 2.90054408549692;
   fWeightMatrix0to1[4][11] = 1.62679158778584;
   fWeightMatrix0to1[5][11] = 1.38266657822798;
   fWeightMatrix0to1[6][11] = -5.67269079623804;
   fWeightMatrix0to1[7][11] = 0.347022310709408;
   fWeightMatrix0to1[8][11] = 2.07418912323777;
   fWeightMatrix0to1[9][11] = -4.6096278019052;
   fWeightMatrix0to1[10][11] = 0.174442154825219;
   fWeightMatrix0to1[11][11] = 6.27481991326056;
   fWeightMatrix0to1[12][11] = 0.759470932013015;
   fWeightMatrix0to1[13][11] = -1.82917361188522;
   fWeightMatrix0to1[14][11] = -0.993425367775605;
   fWeightMatrix0to1[0][12] = -7.53523586443271;
   fWeightMatrix0to1[1][12] = 21.5468775744357;
   fWeightMatrix0to1[2][12] = 0.921025671238286;
   fWeightMatrix0to1[3][12] = 9.28248690275143;
   fWeightMatrix0to1[4][12] = 1.74499830136288;
   fWeightMatrix0to1[5][12] = -1.46254103730028;
   fWeightMatrix0to1[6][12] = -11.1632487098136;
   fWeightMatrix0to1[7][12] = 3.47467667630847;
   fWeightMatrix0to1[8][12] = -0.283691389935999;
   fWeightMatrix0to1[9][12] = -10.9023788004491;
   fWeightMatrix0to1[10][12] = -0.53360932961243;
   fWeightMatrix0to1[11][12] = 6.20422428263981;
   fWeightMatrix0to1[12][12] = 2.46368578447784;
   fWeightMatrix0to1[13][12] = -4.09224474934657;
   fWeightMatrix0to1[14][12] = -0.95898684064953;
   fWeightMatrix0to1[0][13] = -0.0788541991689174;
   fWeightMatrix0to1[1][13] = -6.62084984503802;
   fWeightMatrix0to1[2][13] = 0.860051921072862;
   fWeightMatrix0to1[3][13] = -2.34173306916491;
   fWeightMatrix0to1[4][13] = -1.23830614289846;
   fWeightMatrix0to1[5][13] = -0.582232438929199;
   fWeightMatrix0to1[6][13] = 2.73674113115878;
   fWeightMatrix0to1[7][13] = -0.202060793626291;
   fWeightMatrix0to1[8][13] = -1.90886428352059;
   fWeightMatrix0to1[9][13] = 4.22492333953183;
   fWeightMatrix0to1[10][13] = 0.366646617298999;
   fWeightMatrix0to1[11][13] = -1.91621437121732;
   fWeightMatrix0to1[12][13] = -0.182932670217811;
   fWeightMatrix0to1[13][13] = 3.68678110012327;
   fWeightMatrix0to1[14][13] = 0.71843532493068;
   fWeightMatrix0to1[0][14] = 0.645494929492265;
   fWeightMatrix0to1[1][14] = -1.05423032670736;
   fWeightMatrix0to1[2][14] = -2.04264405618101;
   fWeightMatrix0to1[3][14] = -2.6848388486433;
   fWeightMatrix0to1[4][14] = 2.15889275348426;
   fWeightMatrix0to1[5][14] = 1.44996532959739;
   fWeightMatrix0to1[6][14] = 0.827441875846021;
   fWeightMatrix0to1[7][14] = 0.00430259166284704;
   fWeightMatrix0to1[8][14] = 2.03776716106111;
   fWeightMatrix0to1[9][14] = -1.27622297126903;
   fWeightMatrix0to1[10][14] = -1.13827140728278;
   fWeightMatrix0to1[11][14] = -0.162964381981997;
   fWeightMatrix0to1[12][14] = -1.3495108156184;
   fWeightMatrix0to1[13][14] = 1.81547628824157;
   fWeightMatrix0to1[14][14] = 1.72544487572047;
   fWeightMatrix0to1[0][15] = -0.193745947548535;
   fWeightMatrix0to1[1][15] = 0.14886235685708;
   fWeightMatrix0to1[2][15] = 0.474481953926382;
   fWeightMatrix0to1[3][15] = -3.55457137537068;
   fWeightMatrix0to1[4][15] = -0.658284947522047;
   fWeightMatrix0to1[5][15] = 1.14300148562741;
   fWeightMatrix0to1[6][15] = 0.36126189960153;
   fWeightMatrix0to1[7][15] = 0.507324532748538;
   fWeightMatrix0to1[8][15] = -1.24506168284139;
   fWeightMatrix0to1[9][15] = 2.03256327798991;
   fWeightMatrix0to1[10][15] = -1.37800949339881;
   fWeightMatrix0to1[11][15] = 0.463200126383721;
   fWeightMatrix0to1[12][15] = 0.124983479865452;
   fWeightMatrix0to1[13][15] = -1.80635073890998;
   fWeightMatrix0to1[14][15] = -0.458249948785214;
   fWeightMatrix0to1[0][16] = -3.65302692462694;
   fWeightMatrix0to1[1][16] = 2.72252911762578;
   fWeightMatrix0to1[2][16] = -2.65837224754889;
   fWeightMatrix0to1[3][16] = 1.40531111341226;
   fWeightMatrix0to1[4][16] = -2.15643415191772;
   fWeightMatrix0to1[5][16] = -0.169548614286602;
   fWeightMatrix0to1[6][16] = -2.74937720528084;
   fWeightMatrix0to1[7][16] = -0.928156993856071;
   fWeightMatrix0to1[8][16] = 1.46911243163478;
   fWeightMatrix0to1[9][16] = -2.29491301481521;
   fWeightMatrix0to1[10][16] = -0.154743171742738;
   fWeightMatrix0to1[11][16] = -0.19450271710211;
   fWeightMatrix0to1[12][16] = 0.263090279325454;
   fWeightMatrix0to1[13][16] = 1.54264443331837;
   fWeightMatrix0to1[14][16] = 0.361288522526832;
   fWeightMatrix0to1[0][17] = -1.06632438514851;
   fWeightMatrix0to1[1][17] = -0.137930490462317;
   fWeightMatrix0to1[2][17] = -0.476530055556777;
   fWeightMatrix0to1[3][17] = -4.60922848072828;
   fWeightMatrix0to1[4][17] = -6.20619155504443;
   fWeightMatrix0to1[5][17] = -2.9481074927324;
   fWeightMatrix0to1[6][17] = -0.686955728452742;
   fWeightMatrix0to1[7][17] = -2.45359339956629;
   fWeightMatrix0to1[8][17] = -2.73204179534575;
   fWeightMatrix0to1[9][17] = -0.446424312333947;
   fWeightMatrix0to1[10][17] = -1.63033109747058;
   fWeightMatrix0to1[11][17] = -0.345064845800826;
   fWeightMatrix0to1[12][17] = -3.32348486842156;
   fWeightMatrix0to1[13][17] = -4.29221179210169;
   fWeightMatrix0to1[14][17] = -1.21558831558944;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.2013156530519;
   fWeightMatrix1to2[1][0] = -0.215801478630697;
   fWeightMatrix1to2[2][0] = -1.26404790781407;
   fWeightMatrix1to2[3][0] = 0.629010754142353;
   fWeightMatrix1to2[4][0] = -2.04339749192432;
   fWeightMatrix1to2[5][0] = -0.0219444307944295;
   fWeightMatrix1to2[6][0] = 0.653124482496369;
   fWeightMatrix1to2[7][0] = 0.465805751233404;
   fWeightMatrix1to2[8][0] = 0.376473750188445;
   fWeightMatrix1to2[9][0] = -0.734503782877113;
   fWeightMatrix1to2[10][0] = 0.105215198024614;
   fWeightMatrix1to2[11][0] = 0.146228936010007;
   fWeightMatrix1to2[12][0] = -6.61704469088538;
   fWeightMatrix1to2[13][0] = 2.50812354677529;
   fWeightMatrix1to2[14][0] = -2.33134875037994;
   fWeightMatrix1to2[0][1] = -1.21346639678794;
   fWeightMatrix1to2[1][1] = -1.46079666599425;
   fWeightMatrix1to2[2][1] = 9.02321814380368;
   fWeightMatrix1to2[3][1] = -5.34621512392085;
   fWeightMatrix1to2[4][1] = 2.08467288579461;
   fWeightMatrix1to2[5][1] = -2.75846995917886;
   fWeightMatrix1to2[6][1] = 1.44715549830472;
   fWeightMatrix1to2[7][1] = -1.91453849560875;
   fWeightMatrix1to2[8][1] = -0.256413037304164;
   fWeightMatrix1to2[9][1] = 0.734274754122277;
   fWeightMatrix1to2[10][1] = -2.9088552570744;
   fWeightMatrix1to2[11][1] = -2.5978344744122;
   fWeightMatrix1to2[12][1] = 7.7051320750593;
   fWeightMatrix1to2[13][1] = -14.1219951199926;
   fWeightMatrix1to2[14][1] = -1.46260505312447;
   fWeightMatrix1to2[0][2] = -1.83855956187999;
   fWeightMatrix1to2[1][2] = -0.846621022504539;
   fWeightMatrix1to2[2][2] = 1.26282524812345;
   fWeightMatrix1to2[3][2] = -1.64756812305052;
   fWeightMatrix1to2[4][2] = -0.403755466597982;
   fWeightMatrix1to2[5][2] = -0.918773426278721;
   fWeightMatrix1to2[6][2] = -1.79909664264096;
   fWeightMatrix1to2[7][2] = -2.36206990711794;
   fWeightMatrix1to2[8][2] = -1.62753621358237;
   fWeightMatrix1to2[9][2] = -1.26865186180787;
   fWeightMatrix1to2[10][2] = 2.53472434319569;
   fWeightMatrix1to2[11][2] = -3.68514507948781;
   fWeightMatrix1to2[12][2] = -3.07357339987686;
   fWeightMatrix1to2[13][2] = -2.12703897001572;
   fWeightMatrix1to2[14][2] = -0.335259114200469;
   fWeightMatrix1to2[0][3] = -0.244181574130099;
   fWeightMatrix1to2[1][3] = 0.403223657617361;
   fWeightMatrix1to2[2][3] = -2.51359108941183;
   fWeightMatrix1to2[3][3] = -0.941005116590771;
   fWeightMatrix1to2[4][3] = 1.84614326704246;
   fWeightMatrix1to2[5][3] = -2.16231300091635;
   fWeightMatrix1to2[6][3] = -2.68490840983025;
   fWeightMatrix1to2[7][3] = -0.79661741155259;
   fWeightMatrix1to2[8][3] = -1.6574855560569;
   fWeightMatrix1to2[9][3] = 0.672376385489289;
   fWeightMatrix1to2[10][3] = 1.10424193897369;
   fWeightMatrix1to2[11][3] = -1.39711927306377;
   fWeightMatrix1to2[12][3] = 9.42287766523416;
   fWeightMatrix1to2[13][3] = -3.97955123527722;
   fWeightMatrix1to2[14][3] = 1.21799268798102;
   fWeightMatrix1to2[0][4] = -1.77194920540544;
   fWeightMatrix1to2[1][4] = -1.84519563203119;
   fWeightMatrix1to2[2][4] = -3.39164696873152;
   fWeightMatrix1to2[3][4] = -2.63207473715371;
   fWeightMatrix1to2[4][4] = 0.135812678871138;
   fWeightMatrix1to2[5][4] = 0.687785100496573;
   fWeightMatrix1to2[6][4] = -2.58487928766381;
   fWeightMatrix1to2[7][4] = -0.0470480126350353;
   fWeightMatrix1to2[8][4] = -0.0607253872043529;
   fWeightMatrix1to2[9][4] = -0.688846567408061;
   fWeightMatrix1to2[10][4] = -0.24609199377792;
   fWeightMatrix1to2[11][4] = -0.398243937428605;
   fWeightMatrix1to2[12][4] = 0.992166087327785;
   fWeightMatrix1to2[13][4] = -0.692654173062179;
   fWeightMatrix1to2[14][4] = 0.29707675571638;
   fWeightMatrix1to2[0][5] = -1.91026080939104;
   fWeightMatrix1to2[1][5] = -1.47518853933682;
   fWeightMatrix1to2[2][5] = -0.323688855386892;
   fWeightMatrix1to2[3][5] = -0.0831457410795665;
   fWeightMatrix1to2[4][5] = -2.73763060594922;
   fWeightMatrix1to2[5][5] = 0.941786102057933;
   fWeightMatrix1to2[6][5] = 1.01687105588709;
   fWeightMatrix1to2[7][5] = -0.343211211992345;
   fWeightMatrix1to2[8][5] = -1.35875970565423;
   fWeightMatrix1to2[9][5] = -2.08061888716975;
   fWeightMatrix1to2[10][5] = -1.532819261002;
   fWeightMatrix1to2[11][5] = -2.64934967719905;
   fWeightMatrix1to2[12][5] = -1.10581573594268;
   fWeightMatrix1to2[13][5] = 0.00700082008116041;
   fWeightMatrix1to2[14][5] = -1.86378380124839;
   fWeightMatrix1to2[0][6] = -0.217192153724404;
   fWeightMatrix1to2[1][6] = -2.98184085266636;
   fWeightMatrix1to2[2][6] = -2.10353453216421;
   fWeightMatrix1to2[3][6] = 0.102259427714704;
   fWeightMatrix1to2[4][6] = -0.914651652925045;
   fWeightMatrix1to2[5][6] = -0.282569298680394;
   fWeightMatrix1to2[6][6] = -1.47427423481923;
   fWeightMatrix1to2[7][6] = -1.29963281994944;
   fWeightMatrix1to2[8][6] = -2.18968915300851;
   fWeightMatrix1to2[9][6] = -3.17087757206141;
   fWeightMatrix1to2[10][6] = 4.02672268304842;
   fWeightMatrix1to2[11][6] = -2.85662748554856;
   fWeightMatrix1to2[12][6] = -4.75385413016074;
   fWeightMatrix1to2[13][6] = 8.37999596318072;
   fWeightMatrix1to2[14][6] = -1.2378309516131;
   fWeightMatrix1to2[0][7] = 0.0245233771460002;
   fWeightMatrix1to2[1][7] = -0.954025916070259;
   fWeightMatrix1to2[2][7] = -1.03263400658947;
   fWeightMatrix1to2[3][7] = -0.547876282501216;
   fWeightMatrix1to2[4][7] = -0.608055597941271;
   fWeightMatrix1to2[5][7] = -0.957965083334121;
   fWeightMatrix1to2[6][7] = -1.76273009098274;
   fWeightMatrix1to2[7][7] = -2.51724166048673;
   fWeightMatrix1to2[8][7] = -0.502381584539571;
   fWeightMatrix1to2[9][7] = 0.534691333678704;
   fWeightMatrix1to2[10][7] = -1.29572552467472;
   fWeightMatrix1to2[11][7] = -0.55285772384337;
   fWeightMatrix1to2[12][7] = 2.15166014485142;
   fWeightMatrix1to2[13][7] = 0.0401724140868315;
   fWeightMatrix1to2[14][7] = -2.05362846719655;
   fWeightMatrix1to2[0][8] = 1.54263303427141;
   fWeightMatrix1to2[1][8] = 0.478063768458902;
   fWeightMatrix1to2[2][8] = -3.04547140101342;
   fWeightMatrix1to2[3][8] = -0.377898702786188;
   fWeightMatrix1to2[4][8] = -1.65993880973301;
   fWeightMatrix1to2[5][8] = 0.701487876078811;
   fWeightMatrix1to2[6][8] = -0.16345953302879;
   fWeightMatrix1to2[7][8] = 0.46072294191296;
   fWeightMatrix1to2[8][8] = 1.26328517264491;
   fWeightMatrix1to2[9][8] = -0.857601423185344;
   fWeightMatrix1to2[10][8] = 1.61338043026154;
   fWeightMatrix1to2[11][8] = 1.08670154553599;
   fWeightMatrix1to2[12][8] = -0.97294126156191;
   fWeightMatrix1to2[13][8] = -1.03626278323843;
   fWeightMatrix1to2[14][8] = 1.33274027481016;
   fWeightMatrix1to2[0][9] = -2.37561046550471;
   fWeightMatrix1to2[1][9] = -1.37816139121238;
   fWeightMatrix1to2[2][9] = -3.59745701565846;
   fWeightMatrix1to2[3][9] = 0.289472728350016;
   fWeightMatrix1to2[4][9] = -2.48580806574635;
   fWeightMatrix1to2[5][9] = 0.29075909115868;
   fWeightMatrix1to2[6][9] = -2.44011854650524;
   fWeightMatrix1to2[7][9] = -0.394193275683334;
   fWeightMatrix1to2[8][9] = -3.02741886252643;
   fWeightMatrix1to2[9][9] = -1.48051341340742;
   fWeightMatrix1to2[10][9] = -4.62732012965811;
   fWeightMatrix1to2[11][9] = 4.54160786451802;
   fWeightMatrix1to2[12][9] = -2.17692868508555;
   fWeightMatrix1to2[13][9] = 10.8599906616432;
   fWeightMatrix1to2[14][9] = -1.20002399805644;
   fWeightMatrix1to2[0][10] = -0.591164320205819;
   fWeightMatrix1to2[1][10] = -0.458853636864694;
   fWeightMatrix1to2[2][10] = -0.17531561978243;
   fWeightMatrix1to2[3][10] = -2.88879303933401;
   fWeightMatrix1to2[4][10] = -2.38636586552287;
   fWeightMatrix1to2[5][10] = -0.971163905301219;
   fWeightMatrix1to2[6][10] = -3.02799808701051;
   fWeightMatrix1to2[7][10] = -2.75276446094989;
   fWeightMatrix1to2[8][10] = -2.40701469184626;
   fWeightMatrix1to2[9][10] = 0.433169608728344;
   fWeightMatrix1to2[10][10] = -2.45847185894632;
   fWeightMatrix1to2[11][10] = -2.47439681617284;
   fWeightMatrix1to2[12][10] = -5.14562273555975;
   fWeightMatrix1to2[13][10] = -2.05679959748762;
   fWeightMatrix1to2[14][10] = 1.19364270343433;
   fWeightMatrix1to2[0][11] = 1.89236083072893;
   fWeightMatrix1to2[1][11] = 1.21358583616272;
   fWeightMatrix1to2[2][11] = -1.56744231175815;
   fWeightMatrix1to2[3][11] = -3.68808197290067;
   fWeightMatrix1to2[4][11] = -0.800265052968604;
   fWeightMatrix1to2[5][11] = -1.92135374703978;
   fWeightMatrix1to2[6][11] = -3.08703240009977;
   fWeightMatrix1to2[7][11] = -1.76022717689685;
   fWeightMatrix1to2[8][11] = -0.570955957189886;
   fWeightMatrix1to2[9][11] = -1.38419131022903;
   fWeightMatrix1to2[10][11] = -1.52571243313211;
   fWeightMatrix1to2[11][11] = 0.738410516547207;
   fWeightMatrix1to2[12][11] = -2.17914200950008;
   fWeightMatrix1to2[13][11] = -5.81697924971218;
   fWeightMatrix1to2[14][11] = -0.792685689673984;
   fWeightMatrix1to2[0][12] = 1.55854247517436;
   fWeightMatrix1to2[1][12] = -1.4688424508164;
   fWeightMatrix1to2[2][12] = -0.058578408468586;
   fWeightMatrix1to2[3][12] = 0.908058208704688;
   fWeightMatrix1to2[4][12] = 0.538223796560393;
   fWeightMatrix1to2[5][12] = -1.64577240997681;
   fWeightMatrix1to2[6][12] = 0.356395865113583;
   fWeightMatrix1to2[7][12] = -2.65396145530397;
   fWeightMatrix1to2[8][12] = 0.810597152960304;
   fWeightMatrix1to2[9][12] = 0.814364975933767;
   fWeightMatrix1to2[10][12] = -0.949315238885577;
   fWeightMatrix1to2[11][12] = -0.554257801399328;
   fWeightMatrix1to2[12][12] = -0.552985537018556;
   fWeightMatrix1to2[13][12] = -0.832741508936187;
   fWeightMatrix1to2[14][12] = 1.27455823696153;
   fWeightMatrix1to2[0][13] = -0.132009419402734;
   fWeightMatrix1to2[1][13] = -2.86165420020032;
   fWeightMatrix1to2[2][13] = -1.92866533645199;
   fWeightMatrix1to2[3][13] = 0.566348781791272;
   fWeightMatrix1to2[4][13] = 1.48802878238194;
   fWeightMatrix1to2[5][13] = 0.890590974880831;
   fWeightMatrix1to2[6][13] = -1.14406027287707;
   fWeightMatrix1to2[7][13] = -2.34405452109688;
   fWeightMatrix1to2[8][13] = 0.644992311089795;
   fWeightMatrix1to2[9][13] = -0.527898145030266;
   fWeightMatrix1to2[10][13] = -1.95638662993929;
   fWeightMatrix1to2[11][13] = 0.222213382039404;
   fWeightMatrix1to2[12][13] = 2.48486222711792;
   fWeightMatrix1to2[13][13] = 8.37239421670186;
   fWeightMatrix1to2[14][13] = 0.153199333483316;
   fWeightMatrix1to2[0][14] = -1.00999199530636;
   fWeightMatrix1to2[1][14] = -1.96520167125165;
   fWeightMatrix1to2[2][14] = 1.64061089858943;
   fWeightMatrix1to2[3][14] = 0.862343251810004;
   fWeightMatrix1to2[4][14] = -0.717218810709003;
   fWeightMatrix1to2[5][14] = 0.497306898911869;
   fWeightMatrix1to2[6][14] = -1.83747622410808;
   fWeightMatrix1to2[7][14] = -2.05863865833852;
   fWeightMatrix1to2[8][14] = 0.431188051825061;
   fWeightMatrix1to2[9][14] = 0.105025202938825;
   fWeightMatrix1to2[10][14] = 1.30097448932497;
   fWeightMatrix1to2[11][14] = -2.81686362478286;
   fWeightMatrix1to2[12][14] = -5.35099767104593;
   fWeightMatrix1to2[13][14] = -2.49405078847383;
   fWeightMatrix1to2[14][14] = -1.02495186133657;
   fWeightMatrix1to2[0][15] = -2.48563968717352;
   fWeightMatrix1to2[1][15] = -0.244326424701842;
   fWeightMatrix1to2[2][15] = -2.41120138269441;
   fWeightMatrix1to2[3][15] = -0.527392534398397;
   fWeightMatrix1to2[4][15] = -2.43678722227256;
   fWeightMatrix1to2[5][15] = -1.97717461531046;
   fWeightMatrix1to2[6][15] = 0.152304898189686;
   fWeightMatrix1to2[7][15] = -0.57634124346355;
   fWeightMatrix1to2[8][15] = -1.35031744320415;
   fWeightMatrix1to2[9][15] = -1.99896457873491;
   fWeightMatrix1to2[10][15] = -0.873148680335808;
   fWeightMatrix1to2[11][15] = -0.936278294398518;
   fWeightMatrix1to2[12][15] = -5.77439244237338;
   fWeightMatrix1to2[13][15] = 0.382942970757453;
   fWeightMatrix1to2[14][15] = -2.90693769756756;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.7925473589142;
   fWeightMatrix2to3[0][1] = 2.27279061070202;
   fWeightMatrix2to3[0][2] = -1.3854047852845;
   fWeightMatrix2to3[0][3] = -2.04395838860536;
   fWeightMatrix2to3[0][4] = 1.67747246215286;
   fWeightMatrix2to3[0][5] = -1.65159213402668;
   fWeightMatrix2to3[0][6] = -1.94706480707836;
   fWeightMatrix2to3[0][7] = -0.234416052535359;
   fWeightMatrix2to3[0][8] = -0.0638211357717038;
   fWeightMatrix2to3[0][9] = 1.59592465378411;
   fWeightMatrix2to3[0][10] = -2.56700884975821;
   fWeightMatrix2to3[0][11] = -1.766057268141;
   fWeightMatrix2to3[0][12] = 2.05710912838873;
   fWeightMatrix2to3[0][13] = -4.28316439258808;
   fWeightMatrix2to3[0][14] = 1.0427176495694;
   fWeightMatrix2to3[0][15] = 0.768760093290667;
}

inline double ReadkMLP_pca_ce_600_(n-2)2_no_ev::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = OutputActivationFnc(fWeights[3][o]);
   }

   return fWeights[3][0];
}

double ReadkMLP_pca_ce_600_(n-2)2_no_ev::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadkMLP_pca_ce_600_(n-2)2_no_ev::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadkMLP_pca_ce_600_(n-2)2_no_ev::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 4; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadkMLP_pca_ce_600_(n-2)2_no_ev::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_(n-2)2_no_ev::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 4.87853831146e-05;
   fMax_1[0][0] = 483.144317627;
   fMin_1[1][0] = 8.06744174042e-06;
   fMax_1[1][0] = 492.172912598;
   fMin_1[2][0] = 8.06744174042e-06;
   fMax_1[2][0] = 492.172912598;
   fMin_1[0][1] = 1.23587478811e-05;
   fMax_1[0][1] = 528.975280762;
   fMin_1[1][1] = 1.40066722452e-05;
   fMax_1[1][1] = 414.353363037;
   fMin_1[2][1] = 1.23587478811e-05;
   fMax_1[2][1] = 528.975280762;
   fMin_1[0][2] = -523.870361328;
   fMax_1[0][2] = 358.787536621;
   fMin_1[1][2] = -6712.00195312;
   fMax_1[1][2] = 421.311126709;
   fMin_1[2][2] = -6712.00195312;
   fMax_1[2][2] = 421.311126709;
   fMin_1[0][3] = -272.425018311;
   fMax_1[0][3] = 557.776550293;
   fMin_1[1][3] = -4322.33398438;
   fMax_1[1][3] = 223.121810913;
   fMin_1[2][3] = -4322.33398438;
   fMax_1[2][3] = 557.776550293;
   fMin_1[0][4] = -372.324371338;
   fMax_1[0][4] = 519.056030273;
   fMin_1[1][4] = -294.95513916;
   fMax_1[1][4] = 7005.60400391;
   fMin_1[2][4] = -372.324371338;
   fMax_1[2][4] = 7005.60400391;
   fMin_1[0][5] = -7900.82275391;
   fMax_1[0][5] = 7194.85205078;
   fMin_1[1][5] = -3195.20800781;
   fMax_1[1][5] = 7244.55957031;
   fMin_1[2][5] = -7900.82275391;
   fMax_1[2][5] = 7244.55957031;
   fMin_1[0][6] = -3637.93334961;
   fMax_1[0][6] = 10262.6113281;
   fMin_1[1][6] = -2122.98217773;
   fMax_1[1][6] = 2078.63696289;
   fMin_1[2][6] = -3637.93334961;
   fMax_1[2][6] = 10262.6113281;
   fMin_1[0][7] = -16211.0849609;
   fMax_1[0][7] = 3770.25610352;
   fMin_1[1][7] = -10211.4736328;
   fMax_1[1][7] = 1888.3873291;
   fMin_1[2][7] = -16211.0849609;
   fMax_1[2][7] = 3770.25610352;
   fMin_1[0][8] = -38084.8515625;
   fMax_1[0][8] = 3137.67016602;
   fMin_1[1][8] = -3483.88232422;
   fMax_1[1][8] = 6029.96435547;
   fMin_1[2][8] = -38084.8515625;
   fMax_1[2][8] = 6029.96435547;
   fMin_1[0][9] = -94022.8125;
   fMax_1[0][9] = 8030.11816406;
   fMin_1[1][9] = -6661.46386719;
   fMax_1[1][9] = 3972.78491211;
   fMin_1[2][9] = -94022.8125;
   fMax_1[2][9] = 8030.11816406;
   fMin_1[0][10] = -44827.8710938;
   fMax_1[0][10] = 7534.72558594;
   fMin_1[1][10] = -4591.98974609;
   fMax_1[1][10] = 2715.74853516;
   fMin_1[2][10] = -44827.8710938;
   fMax_1[2][10] = 7534.72558594;
   fMin_1[0][11] = 0.0220243129879;
   fMax_1[0][11] = 179.991531372;
   fMin_1[1][11] = 0.0261516775936;
   fMax_1[1][11] = 179.984313965;
   fMin_1[2][11] = 0.0220243129879;
   fMax_1[2][11] = 179.991531372;
   fMin_1[0][12] = 0.00406167190522;
   fMax_1[0][12] = 486.957427979;
   fMin_1[1][12] = 0.00610703369603;
   fMax_1[1][12] = 5657.98974609;
   fMin_1[2][12] = 0.00406167190522;
   fMax_1[2][12] = 5657.98974609;
   fMin_1[0][13] = 0.0120389293879;
   fMax_1[0][13] = 642.034057617;
   fMin_1[1][13] = 0.00498456507921;
   fMax_1[1][13] = 7820.19091797;
   fMin_1[2][13] = 0.00498456507921;
   fMax_1[2][13] = 7820.19091797;
   fMin_1[0][14] = 0.00987958256155;
   fMax_1[0][14] = 518.758972168;
   fMin_1[1][14] = 0.00600005546585;
   fMax_1[1][14] = 6695.12744141;
   fMin_1[2][14] = 0.00600005546585;
   fMax_1[2][14] = 6695.12744141;
   fMin_1[0][15] = 0.0117067871615;
   fMax_1[0][15] = 18368.9785156;
   fMin_1[1][15] = 0.00836985651404;
   fMax_1[1][15] = 11955.8955078;
   fMin_1[2][15] = 0.00836985651404;
   fMax_1[2][15] = 18368.9785156;
   fMin_1[0][16] = 0.127350762486;
   fMax_1[0][16] = 110893.085938;
   fMin_1[1][16] = 0.0658141672611;
   fMax_1[1][16] = 10702.3935547;
   fMin_1[2][16] = 0.0658141672611;
   fMax_1[2][16] = 110893.085938;
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_(n-2)2_no_ev::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 17;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
      indicesGet.push_back( 15);
      indicesGet.push_back( 16);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
      indicesPut.push_back( 15);
      indicesPut.push_back( 16);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<17;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_(n-2)2_no_ev::X2P_2( const double* x, double* p, int index ) const
{
   // Calculate the principal components from the original data vector
   // x, and return it in p (function extracted from TPrincipal::X2P)
   // It's the users responsibility to make sure that both x and p are
   // of the right size (i.e., memory must be allocated for p).
   const int nVar = 17;

   for (int i = 0; i < nVar; i++) {
      p[i] = 0;
      for (int j = 0; j < nVar; j++) p[i] += (x[j] - fMeanValues_2[index][j]) * fEigenVectors_2[index][j][i];
   }
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_(n-2)2_no_ev::InitTransform_2()
{
   // PCA transformation, initialisation
   // initialise vector of mean values
   fMeanValues_2[0][0] = -0.963369317202;
   fMeanValues_2[0][1] = -0.972456201031;
   fMeanValues_2[0][2] = 0.882436230682;
   fMeanValues_2[0][3] = 0.771397908671;
   fMeanValues_2[0][4] = -0.906861330328;
   fMeanValues_2[0][5] = 0.0435853841103;
   fMeanValues_2[0][6] = -0.476564491319;
   fMeanValues_2[0][7] = 0.619633323722;
   fMeanValues_2[0][8] = 0.726709822471;
   fMeanValues_2[0][9] = 0.842620376619;
   fMeanValues_2[0][10] = 0.711161884816;
   fMeanValues_2[0][11] = -0.0390649040805;
   fMeanValues_2[0][12] = -0.997244944241;
   fMeanValues_2[0][13] = -0.997324159637;
   fMeanValues_2[0][14] = -0.997823402705;
   fMeanValues_2[0][15] = -0.998510151302;
   fMeanValues_2[0][16] = -0.999614665498;
   fMeanValues_2[1][0] = -0.968415679367;
   fMeanValues_2[1][1] = -0.976517851628;
   fMeanValues_2[1][2] = 0.88248449099;
   fMeanValues_2[1][3] = 0.771415530053;
   fMeanValues_2[1][4] = -0.906821323792;
   fMeanValues_2[1][5] = 0.0436223006451;
   fMeanValues_2[1][6] = -0.476557325789;
   fMeanValues_2[1][7] = 0.619642145687;
   fMeanValues_2[1][8] = 0.726726188322;
   fMeanValues_2[1][9] = 0.84262823421;
   fMeanValues_2[1][10] = 0.711080613805;
   fMeanValues_2[1][11] = 0.0214365948919;
   fMeanValues_2[1][12] = -0.997417806109;
   fMeanValues_2[1][13] = -0.997830167617;
   fMeanValues_2[1][14] = -0.997917993684;
   fMeanValues_2[1][15] = -0.998710182102;
   fMeanValues_2[1][16] = -0.999696948844;
   fMeanValues_2[2][0] = -0.965892498284;
   fMeanValues_2[2][1] = -0.97448702633;
   fMeanValues_2[2][2] = 0.882460360836;
   fMeanValues_2[2][3] = 0.771406719362;
   fMeanValues_2[2][4] = -0.90684132706;
   fMeanValues_2[2][5] = 0.0436038423777;
   fMeanValues_2[2][6] = -0.476560908554;
   fMeanValues_2[2][7] = 0.619637734705;
   fMeanValues_2[2][8] = 0.726718005396;
   fMeanValues_2[2][9] = 0.842624305415;
   fMeanValues_2[2][10] = 0.711121249311;
   fMeanValues_2[2][11] = -0.0088141545943;
   fMeanValues_2[2][12] = -0.997331375175;
   fMeanValues_2[2][13] = -0.997577163627;
   fMeanValues_2[2][14] = -0.997870698194;
   fMeanValues_2[2][15] = -0.998610166702;
   fMeanValues_2[2][16] = -0.999655807171;

   // initialise matrix of eigenvectors
   fEigenVectors_2[0][0][0] = -0.00120313685414;
   fEigenVectors_2[0][0][1] = 0.998921957304;
   fEigenVectors_2[0][0][2] = -0.0100458878374;
   fEigenVectors_2[0][0][3] = -0.0055987556681;
   fEigenVectors_2[0][0][4] = 0.00688520599486;
   fEigenVectors_2[0][0][5] = 0.0163024904961;
   fEigenVectors_2[0][0][6] = -0.00332533511454;
   fEigenVectors_2[0][0][7] = 0.0405190985481;
   fEigenVectors_2[0][0][8] = -0.00441023675488;
   fEigenVectors_2[0][0][9] = -0.00495013046477;
   fEigenVectors_2[0][0][10] = -0.000261206277945;
   fEigenVectors_2[0][0][11] = 0.00162584311452;
   fEigenVectors_2[0][0][12] = 0.00238936694927;
   fEigenVectors_2[0][0][13] = 0.000762958339449;
   fEigenVectors_2[0][0][14] = 0.00114537475438;
   fEigenVectors_2[0][0][15] = -0.000666604857469;
   fEigenVectors_2[0][0][16] = -0.000681389471786;
   fEigenVectors_2[0][1][0] = 0.0001665384409;
   fEigenVectors_2[0][1][1] = 0.00956004711444;
   fEigenVectors_2[0][1][2] = 0.999738455424;
   fEigenVectors_2[0][1][3] = -0.00604248915773;
   fEigenVectors_2[0][1][4] = 0.013694576366;
   fEigenVectors_2[0][1][5] = 0.0101581657111;
   fEigenVectors_2[0][1][6] = -0.00214120094792;
   fEigenVectors_2[0][1][7] = 0.00345688873912;
   fEigenVectors_2[0][1][8] = -0.00174903613835;
   fEigenVectors_2[0][1][9] = -0.0089037924583;
   fEigenVectors_2[0][1][10] = -0.00220332438205;
   fEigenVectors_2[0][1][11] = -0.000598813037486;
   fEigenVectors_2[0][1][12] = 0.000496998939943;
   fEigenVectors_2[0][1][13] = -1.76072934727e-06;
   fEigenVectors_2[0][1][14] = 0.000144573568777;
   fEigenVectors_2[0][1][15] = -4.12784326343e-05;
   fEigenVectors_2[0][1][16] = -5.27400189633e-05;
   fEigenVectors_2[0][2][0] = 8.2579391227e-06;
   fEigenVectors_2[0][2][1] = -5.26804475415e-05;
   fEigenVectors_2[0][2][2] = 0.000122347785612;
   fEigenVectors_2[0][2][3] = -0.00248209841567;
   fEigenVectors_2[0][2][4] = -0.00276250202852;
   fEigenVectors_2[0][2][5] = -0.00911442671281;
   fEigenVectors_2[0][2][6] = -0.0133396386062;
   fEigenVectors_2[0][2][7] = -0.0601264042558;
   fEigenVectors_2[0][2][8] = -0.0463232017629;
   fEigenVectors_2[0][2][9] = 0.0212920589228;
   fEigenVectors_2[0][2][10] = 0.0703497245454;
   fEigenVectors_2[0][2][11] = 0.0799088357725;
   fEigenVectors_2[0][2][12] = 0.98562329584;
   fEigenVectors_2[0][2][13] = 0.0926341607253;
   fEigenVectors_2[0][2][14] = -0.043955464599;
   fEigenVectors_2[0][2][15] = -0.0087274384882;
   fEigenVectors_2[0][2][16] = -0.0115615776313;
   fEigenVectors_2[0][3][0] = 3.7534568234e-05;
   fEigenVectors_2[0][3][1] = -2.89235160117e-05;
   fEigenVectors_2[0][3][2] = -3.57500663761e-05;
   fEigenVectors_2[0][3][3] = 0.00112444812067;
   fEigenVectors_2[0][3][4] = -0.00623570243455;
   fEigenVectors_2[0][3][5] = 0.0207634083741;
   fEigenVectors_2[0][3][6] = -0.0457576299342;
   fEigenVectors_2[0][3][7] = 0.01904863492;
   fEigenVectors_2[0][3][8] = 0.517633736226;
   fEigenVectors_2[0][3][9] = -0.275546869376;
   fEigenVectors_2[0][3][10] = 0.807419064938;
   fEigenVectors_2[0][3][11] = 0.00678906073477;
   fEigenVectors_2[0][3][12] = -0.0254219175072;
   fEigenVectors_2[0][3][13] = -0.0140471163873;
   fEigenVectors_2[0][3][14] = 0.0089171228838;
   fEigenVectors_2[0][3][15] = 0.0154451741114;
   fEigenVectors_2[0][3][16] = -0.00824948883899;
   fEigenVectors_2[0][4][0] = -0.000105755775235;
   fEigenVectors_2[0][4][1] = -0.000666308783149;
   fEigenVectors_2[0][4][2] = -0.000554496832693;
   fEigenVectors_2[0][4][3] = -0.225495213843;
   fEigenVectors_2[0][4][4] = 0.263176831485;
   fEigenVectors_2[0][4][5] = -0.808473587481;
   fEigenVectors_2[0][4][6] = 0.0989064337731;
   fEigenVectors_2[0][4][7] = 0.213089737576;
   fEigenVectors_2[0][4][8] = -0.202805157225;
   fEigenVectors_2[0][4][9] = -0.337861166716;
   fEigenVectors_2[0][4][10] = 0.0382824112225;
   fEigenVectors_2[0][4][11] = -0.00659679012947;
   fEigenVectors_2[0][4][12] = 0.00953494739181;
   fEigenVectors_2[0][4][13] = -0.101297306652;
   fEigenVectors_2[0][4][14] = -0.0501623341209;
   fEigenVectors_2[0][4][15] = -0.0375542670172;
   fEigenVectors_2[0][4][16] = -0.00142759040883;
   fEigenVectors_2[0][5][0] = 8.527323937e-06;
   fEigenVectors_2[0][5][1] = -3.81024142417e-05;
   fEigenVectors_2[0][5][2] = -0.000622970162993;
   fEigenVectors_2[0][5][3] = -0.0388231924614;
   fEigenVectors_2[0][5][4] = 0.0890794244102;
   fEigenVectors_2[0][5][5] = -0.00474098513183;
   fEigenVectors_2[0][5][6] = -0.680663435699;
   fEigenVectors_2[0][5][7] = -0.0995788065201;
   fEigenVectors_2[0][5][8] = -0.554802618729;
   fEigenVectors_2[0][5][9] = 0.221553877336;
   fEigenVectors_2[0][5][10] = 0.39362894388;
   fEigenVectors_2[0][5][11] = -0.0145802734239;
   fEigenVectors_2[0][5][12] = -0.0723078131039;
   fEigenVectors_2[0][5][13] = -0.00543724608648;
   fEigenVectors_2[0][5][14] = 0.00297667107033;
   fEigenVectors_2[0][5][15] = 0.000811558768828;
   fEigenVectors_2[0][5][16] = -0.000446192673101;
   fEigenVectors_2[0][6][0] = -1.78138060633e-06;
   fEigenVectors_2[0][6][1] = 0.000144856162398;
   fEigenVectors_2[0][6][2] = -0.000684254188324;
   fEigenVectors_2[0][6][3] = 0.0505167609651;
   fEigenVectors_2[0][6][4] = -0.128310878793;
   fEigenVectors_2[0][6][5] = -0.149323456839;
   fEigenVectors_2[0][6][6] = -0.716906853618;
   fEigenVectors_2[0][6][7] = 0.0345323252432;
   fEigenVectors_2[0][6][8] = 0.440479329446;
   fEigenVectors_2[0][6][9] = -0.275677822864;
   fEigenVectors_2[0][6][10] = -0.413725704743;
   fEigenVectors_2[0][6][11] = 0.0170285989194;
   fEigenVectors_2[0][6][12] = 0.0450583725844;
   fEigenVectors_2[0][6][13] = 0.00456403835582;
   fEigenVectors_2[0][6][14] = -0.00256216719278;
   fEigenVectors_2[0][6][15] = -0.000813378273812;
   fEigenVectors_2[0][6][16] = 0.00096215141793;
   fEigenVectors_2[0][7][0] = -7.42676677144e-05;
   fEigenVectors_2[0][7][1] = -0.000770315617484;
   fEigenVectors_2[0][7][2] = -6.14920786367e-05;
   fEigenVectors_2[0][7][3] = -0.251003228023;
   fEigenVectors_2[0][7][4] = 0.482223369132;
   fEigenVectors_2[0][7][5] = -0.156336750673;
   fEigenVectors_2[0][7][6] = -0.0638251515116;
   fEigenVectors_2[0][7][7] = 0.0903760031437;
   fEigenVectors_2[0][7][8] = 0.418526781946;
   fEigenVectors_2[0][7][9] = 0.7012733216;
   fEigenVectors_2[0][7][10] = -0.0262340022616;
   fEigenVectors_2[0][7][11] = -0.000803096431421;
   fEigenVectors_2[0][7][12] = 0.00993590769083;
   fEigenVectors_2[0][7][13] = 0.00327802084369;
   fEigenVectors_2[0][7][14] = -0.00142745550724;
   fEigenVectors_2[0][7][15] = -0.00323228111648;
   fEigenVectors_2[0][7][16] = -0.00387143341956;
   fEigenVectors_2[0][8][0] = -2.14492977987e-05;
   fEigenVectors_2[0][8][1] = -0.000231785895809;
   fEigenVectors_2[0][8][2] = 5.8432826205e-06;
   fEigenVectors_2[0][8][3] = -0.425213919509;
   fEigenVectors_2[0][8][4] = -0.221557935945;
   fEigenVectors_2[0][8][5] = 0.0654427105126;
   fEigenVectors_2[0][8][6] = -0.00437223944257;
   fEigenVectors_2[0][8][7] = -0.0467095651255;
   fEigenVectors_2[0][8][8] = 0.00460292163961;
   fEigenVectors_2[0][8][9] = 0.0208097626902;
   fEigenVectors_2[0][8][10] = -0.013150426907;
   fEigenVectors_2[0][8][11] = 0.0122550879237;
   fEigenVectors_2[0][8][12] = 0.0831550762111;
   fEigenVectors_2[0][8][13] = -0.640079110073;
   fEigenVectors_2[0][8][14] = 0.580967268142;
   fEigenVectors_2[0][8][15] = 0.0562962138209;
   fEigenVectors_2[0][8][16] = 0.0744035142487;
   fEigenVectors_2[0][9][0] = -8.4061389749e-06;
   fEigenVectors_2[0][9][1] = -7.38709037248e-05;
   fEigenVectors_2[0][9][2] = 9.51046350947e-05;
   fEigenVectors_2[0][9][3] = -0.437956100635;
   fEigenVectors_2[0][9][4] = -0.226973016937;
   fEigenVectors_2[0][9][5] = 0.0638946438725;
   fEigenVectors_2[0][9][6] = -0.00345987432053;
   fEigenVectors_2[0][9][7] = -0.0468245074474;
   fEigenVectors_2[0][9][8] = 0.0169110507415;
   fEigenVectors_2[0][9][9] = 0.00639944558402;
   fEigenVectors_2[0][9][10] = 0.0107235128751;
   fEigenVectors_2[0][9][11] = -0.0138978759966;
   fEigenVectors_2[0][9][12] = -0.02949241084;
   fEigenVectors_2[0][9][13] = 0.125311519848;
   fEigenVectors_2[0][9][14] = -0.224447127451;
   fEigenVectors_2[0][9][15] = -0.800275030851;
   fEigenVectors_2[0][9][16] = 0.205830414729;
   fEigenVectors_2[0][10][0] = 0.000844196377947;
   fEigenVectors_2[0][10][1] = -0.000110229059684;
   fEigenVectors_2[0][10][2] = 1.52426486893e-05;
   fEigenVectors_2[0][10][3] = -0.441183873097;
   fEigenVectors_2[0][10][4] = -0.17811181574;
   fEigenVectors_2[0][10][5] = -0.0506174171303;
   fEigenVectors_2[0][10][6] = 0.0110167671127;
   fEigenVectors_2[0][10][7] = -0.0255730956141;
   fEigenVectors_2[0][10][8] = -0.0150857453008;
   fEigenVectors_2[0][10][9] = -0.0337881735782;
   fEigenVectors_2[0][10][10] = 0.00192549777985;
   fEigenVectors_2[0][10][11] = -0.0749990215324;
   fEigenVectors_2[0][10][12] = -0.0451234429193;
   fEigenVectors_2[0][10][13] = 0.721102440204;
   fEigenVectors_2[0][10][14] = 0.38286593749;
   fEigenVectors_2[0][10][15] = 0.305892240682;
   fEigenVectors_2[0][10][16] = 0.0334027894565;
   fEigenVectors_2[0][11][0] = -0.999998857262;
   fEigenVectors_2[0][11][1] = -0.00119340017225;
   fEigenVectors_2[0][11][2] = 0.000179260421955;
   fEigenVectors_2[0][11][3] = -0.000287178020448;
   fEigenVectors_2[0][11][4] = -0.000195990330543;
   fEigenVectors_2[0][11][5] = -2.94762278238e-06;
   fEigenVectors_2[0][11][6] = 9.84297110134e-06;
   fEigenVectors_2[0][11][7] = -0.000241636018004;
   fEigenVectors_2[0][11][8] = 1.2351490594e-05;
   fEigenVectors_2[0][11][9] = -5.13630030219e-05;
   fEigenVectors_2[0][11][10] = 3.0026097718e-05;
   fEigenVectors_2[0][11][11] = -0.000287653766166;
   fEigenVectors_2[0][11][12] = -2.65512842219e-05;
   fEigenVectors_2[0][11][13] = 0.000624189411292;
   fEigenVectors_2[0][11][14] = 0.000340111223237;
   fEigenVectors_2[0][11][15] = 0.000236922649678;
   fEigenVectors_2[0][11][16] = -3.45924276023e-05;
   fEigenVectors_2[0][12][0] = 1.50961757848e-05;
   fEigenVectors_2[0][12][1] = 0.0261272163306;
   fEigenVectors_2[0][12][2] = 0.00447301092828;
   fEigenVectors_2[0][12][3] = 0.0122460938511;
   fEigenVectors_2[0][12][4] = -0.00809813772208;
   fEigenVectors_2[0][12][5] = -0.185526081436;
   fEigenVectors_2[0][12][6] = 0.0461534923282;
   fEigenVectors_2[0][12][7] = -0.586360726849;
   fEigenVectors_2[0][12][8] = 0.0451599933065;
   fEigenVectors_2[0][12][9] = 0.0190911628025;
   fEigenVectors_2[0][12][10] = -0.0113542995927;
   fEigenVectors_2[0][12][11] = 0.522568236548;
   fEigenVectors_2[0][12][12] = -0.0838144143517;
   fEigenVectors_2[0][12][13] = 0.0498043667447;
   fEigenVectors_2[0][12][14] = 0.119187025617;
   fEigenVectors_2[0][12][15] = -0.155515083704;
   fEigenVectors_2[0][12][16] = -0.543329220023;
   fEigenVectors_2[0][13][0] = 0.000271452734329;
   fEigenVectors_2[0][13][1] = 0.0275591258246;
   fEigenVectors_2[0][13][2] = 0.00312783754177;
   fEigenVectors_2[0][13][3] = 0.0145696989369;
   fEigenVectors_2[0][13][4] = -0.00205170811064;
   fEigenVectors_2[0][13][5] = -0.152988320174;
   fEigenVectors_2[0][13][6] = 0.0360698721381;
   fEigenVectors_2[0][13][7] = -0.572573000457;
   fEigenVectors_2[0][13][8] = 0.0672303594987;
   fEigenVectors_2[0][13][9] = 0.00717558964868;
   fEigenVectors_2[0][13][10] = -0.0151374083237;
   fEigenVectors_2[0][13][11] = -0.78786901093;
   fEigenVectors_2[0][13][12] = 0.0340907360017;
   fEigenVectors_2[0][13][13] = -0.0647202754589;
   fEigenVectors_2[0][13][14] = -0.0667495304632;
   fEigenVectors_2[0][13][15] = 0.00899781106532;
   fEigenVectors_2[0][13][16] = -0.105082665843;
   fEigenVectors_2[0][14][0] = -4.97319681499e-05;
   fEigenVectors_2[0][14][1] = 0.0227113239051;
   fEigenVectors_2[0][14][2] = 0.0036979502797;
   fEigenVectors_2[0][14][3] = 0.00997769808298;
   fEigenVectors_2[0][14][4] = -0.0087355596827;
   fEigenVectors_2[0][14][5] = -0.146069022769;
   fEigenVectors_2[0][14][6] = 0.0358035809792;
   fEigenVectors_2[0][14][7] = -0.473874983298;
   fEigenVectors_2[0][14][8] = 0.0435798954102;
   fEigenVectors_2[0][14][9] = 0.0213143368708;
   fEigenVectors_2[0][14][10] = -0.00347406562874;
   fEigenVectors_2[0][14][11] = 0.298532142575;
   fEigenVectors_2[0][14][12] = -0.0456195995458;
   fEigenVectors_2[0][14][13] = -0.0378591320929;
   fEigenVectors_2[0][14][14] = -0.180203722865;
   fEigenVectors_2[0][14][15] = 0.248081453603;
   fEigenVectors_2[0][14][16] = 0.750399779952;
   fEigenVectors_2[0][15][0] = -7.15521973304e-06;
   fEigenVectors_2[0][15][1] = 0.00975613840129;
   fEigenVectors_2[0][15][2] = 0.0194247430953;
   fEigenVectors_2[0][15][3] = 0.289599734228;
   fEigenVectors_2[0][15][4] = -0.692509164037;
   fEigenVectors_2[0][15][5] = -0.446954384578;
   fEigenVectors_2[0][15][6] = 0.0406388770193;
   fEigenVectors_2[0][15][7] = 0.166000609095;
   fEigenVectors_2[0][15][8] = 0.0526374795396;
   fEigenVectors_2[0][15][9] = 0.435636771515;
   fEigenVectors_2[0][15][10] = 0.11892150748;
   fEigenVectors_2[0][15][11] = -0.0181196656889;
   fEigenVectors_2[0][15][12] = -0.00863394115004;
   fEigenVectors_2[0][15][13] = -0.000393323226563;
   fEigenVectors_2[0][15][14] = 0.000412199656718;
   fEigenVectors_2[0][15][15] = -0.00199985182545;
   fEigenVectors_2[0][15][16] = -0.0038715831718;
   fEigenVectors_2[0][16][0] = 4.80705117647e-05;
   fEigenVectors_2[0][16][1] = 0.00280115315471;
   fEigenVectors_2[0][16][2] = 0.000298281585793;
   fEigenVectors_2[0][16][3] = 0.480030522427;
   fEigenVectors_2[0][16][4] = 0.247940962615;
   fEigenVectors_2[0][16][5] = -0.0941754983707;
   fEigenVectors_2[0][16][6] = 0.00901759121809;
   fEigenVectors_2[0][16][7] = -0.0297310402672;
   fEigenVectors_2[0][16][8] = 0.000611721952326;
   fEigenVectors_2[0][16][9] = -0.0152533889107;
   fEigenVectors_2[0][16][10] = 0.00706297619397;
   fEigenVectors_2[0][16][11] = -0.0615271301009;
   fEigenVectors_2[0][16][12] = 0.0168152468594;
   fEigenVectors_2[0][16][13] = 0.165537621724;
   fEigenVectors_2[0][16][14] = 0.640181869961;
   fEigenVectors_2[0][16][15] = -0.418651316605;
   fEigenVectors_2[0][16][16] = 0.2853034191;
   fEigenVectors_2[1][0][0] = -0.000473816375828;
   fEigenVectors_2[1][0][1] = 0.998254762176;
   fEigenVectors_2[1][0][2] = -0.0350363341387;
   fEigenVectors_2[1][0][3] = -0.0349963319252;
   fEigenVectors_2[1][0][4] = -0.0197661958875;
   fEigenVectors_2[1][0][5] = -0.000285929953436;
   fEigenVectors_2[1][0][6] = 0.0228868862695;
   fEigenVectors_2[1][0][7] = 0.00658282228361;
   fEigenVectors_2[1][0][8] = 0.00224270093697;
   fEigenVectors_2[1][0][9] = 0.00122592722387;
   fEigenVectors_2[1][0][10] = -0.00757967868466;
   fEigenVectors_2[1][0][11] = -0.00266771785855;
   fEigenVectors_2[1][0][12] = -0.000933574112242;
   fEigenVectors_2[1][0][13] = 0.00110424171954;
   fEigenVectors_2[1][0][14] = 0.00185112901811;
   fEigenVectors_2[1][0][15] = 0.000561332925811;
   fEigenVectors_2[1][0][16] = 0.000237548262044;
   fEigenVectors_2[1][1][0] = 0.000236460898938;
   fEigenVectors_2[1][1][1] = 0.0344876259212;
   fEigenVectors_2[1][1][2] = 0.999187354669;
   fEigenVectors_2[1][1][3] = -0.00591525091869;
   fEigenVectors_2[1][1][4] = -0.00874178281739;
   fEigenVectors_2[1][1][5] = -0.0112912523615;
   fEigenVectors_2[1][1][6] = 0.00421035552114;
   fEigenVectors_2[1][1][7] = 0.0124567933722;
   fEigenVectors_2[1][1][8] = -0.00213553434438;
   fEigenVectors_2[1][1][9] = 0.00290421337759;
   fEigenVectors_2[1][1][10] = -0.00164288824535;
   fEigenVectors_2[1][1][11] = -0.00275559884834;
   fEigenVectors_2[1][1][12] = -2.37245192617e-05;
   fEigenVectors_2[1][1][13] = 9.47837551016e-05;
   fEigenVectors_2[1][1][14] = 0.00016826016123;
   fEigenVectors_2[1][1][15] = 0.000229455702131;
   fEigenVectors_2[1][1][16] = 1.1971539464e-06;
   fEigenVectors_2[1][2][0] = 1.1576509935e-05;
   fEigenVectors_2[1][2][1] = -0.000528158072233;
   fEigenVectors_2[1][2][2] = 0.000153991007316;
   fEigenVectors_2[1][2][3] = -0.303914866523;
   fEigenVectors_2[1][2][4] = -0.121686856234;
   fEigenVectors_2[1][2][5] = 0.124007348923;
   fEigenVectors_2[1][2][6] = -0.397863928613;
   fEigenVectors_2[1][2][7] = -0.100611926119;
   fEigenVectors_2[1][2][8] = -0.770852201942;
   fEigenVectors_2[1][2][9] = -0.19968212511;
   fEigenVectors_2[1][2][10] = 0.179032039391;
   fEigenVectors_2[1][2][11] = -0.198850681975;
   fEigenVectors_2[1][2][12] = 0.0225415845776;
   fEigenVectors_2[1][2][13] = 0.035837311599;
   fEigenVectors_2[1][2][14] = 0.0383304073085;
   fEigenVectors_2[1][2][15] = 0.00916567683103;
   fEigenVectors_2[1][2][16] = 0.00238186911108;
   fEigenVectors_2[1][3][0] = -3.30069831084e-05;
   fEigenVectors_2[1][3][1] = -0.000687231599883;
   fEigenVectors_2[1][3][2] = -0.00012280065659;
   fEigenVectors_2[1][3][3] = -0.337342976946;
   fEigenVectors_2[1][3][4] = -0.157589166501;
   fEigenVectors_2[1][3][5] = 0.15037313451;
   fEigenVectors_2[1][3][6] = -0.729974039833;
   fEigenVectors_2[1][3][7] = 0.14498513239;
   fEigenVectors_2[1][3][8] = 0.473366172777;
   fEigenVectors_2[1][3][9] = 0.244202712412;
   fEigenVectors_2[1][3][10] = -0.0186665161847;
   fEigenVectors_2[1][3][11] = -0.00206725854573;
   fEigenVectors_2[1][3][12] = -0.016353313703;
   fEigenVectors_2[1][3][13] = 0.00350898696715;
   fEigenVectors_2[1][3][14] = 0.017318535424;
   fEigenVectors_2[1][3][15] = 0.00141730183589;
   fEigenVectors_2[1][3][16] = -0.0150040023788;
   fEigenVectors_2[1][4][0] = 0.000246031679747;
   fEigenVectors_2[1][4][1] = 0.000838590873156;
   fEigenVectors_2[1][4][2] = -0.000944051770906;
   fEigenVectors_2[1][4][3] = 0.498579656351;
   fEigenVectors_2[1][4][4] = -0.690555105667;
   fEigenVectors_2[1][4][5] = 0.405093340734;
   fEigenVectors_2[1][4][6] = 0.0367969815662;
   fEigenVectors_2[1][4][7] = 0.0946636092558;
   fEigenVectors_2[1][4][8] = -0.0103177857712;
   fEigenVectors_2[1][4][9] = 0.051009813743;
   fEigenVectors_2[1][4][10] = -0.078695499535;
   fEigenVectors_2[1][4][11] = -0.274220654861;
   fEigenVectors_2[1][4][12] = -0.0620407930322;
   fEigenVectors_2[1][4][13] = 0.10461302347;
   fEigenVectors_2[1][4][14] = 0.0278380714433;
   fEigenVectors_2[1][4][15] = -0.019364174759;
   fEigenVectors_2[1][4][16] = -0.00965425651;
   fEigenVectors_2[1][5][0] = 2.06806974148e-06;
   fEigenVectors_2[1][5][1] = -0.000204799990361;
   fEigenVectors_2[1][5][2] = -0.000257411665133;
   fEigenVectors_2[1][5][3] = -0.00320856377648;
   fEigenVectors_2[1][5][4] = 0.170786275894;
   fEigenVectors_2[1][5][5] = 0.479771187674;
   fEigenVectors_2[1][5][6] = 0.0996608320241;
   fEigenVectors_2[1][5][7] = 0.556897796424;
   fEigenVectors_2[1][5][8] = -0.25606646678;
   fEigenVectors_2[1][5][9] = 0.285915024127;
   fEigenVectors_2[1][5][10] = 0.0997226467218;
   fEigenVectors_2[1][5][11] = 0.513128764869;
   fEigenVectors_2[1][5][12] = -0.00194833091267;
   fEigenVectors_2[1][5][13] = 0.000106271864919;
   fEigenVectors_2[1][5][14] = -0.00159049508577;
   fEigenVectors_2[1][5][15] = -0.002020057329;
   fEigenVectors_2[1][5][16] = -0.000474998707508;
   fEigenVectors_2[1][6][0] = -6.98338924759e-06;
   fEigenVectors_2[1][6][1] = 6.33473183775e-05;
   fEigenVectors_2[1][6][2] = -0.000155618143964;
   fEigenVectors_2[1][6][3] = -0.00367336573048;
   fEigenVectors_2[1][6][4] = 0.0350711973992;
   fEigenVectors_2[1][6][5] = 0.116743448988;
   fEigenVectors_2[1][6][6] = -0.0537356207155;
   fEigenVectors_2[1][6][7] = 0.411535837255;
   fEigenVectors_2[1][6][8] = 0.21576593902;
   fEigenVectors_2[1][6][9] = -0.874093990242;
   fEigenVectors_2[1][6][10] = 0.0365488136599;
   fEigenVectors_2[1][6][11] = 0.0305691012604;
   fEigenVectors_2[1][6][12] = 0.00221089191145;
   fEigenVectors_2[1][6][13] = 0.000517807187654;
   fEigenVectors_2[1][6][14] = -0.00148978841023;
   fEigenVectors_2[1][6][15] = 0.000163842621411;
   fEigenVectors_2[1][6][16] = 0.00229382368549;
   fEigenVectors_2[1][7][0] = 7.79182017759e-05;
   fEigenVectors_2[1][7][1] = -0.000295248220378;
   fEigenVectors_2[1][7][2] = -0.000447415695171;
   fEigenVectors_2[1][7][3] = 0.052261071013;
   fEigenVectors_2[1][7][4] = -0.484178969381;
   fEigenVectors_2[1][7][5] = -0.262984309187;
   fEigenVectors_2[1][7][6] = -0.0880027973291;
   fEigenVectors_2[1][7][7] = -0.263439446253;
   fEigenVectors_2[1][7][8] = -0.01124825174;
   fEigenVectors_2[1][7][9] = -0.141263614185;
   fEigenVectors_2[1][7][10] = 0.214976518019;
   fEigenVectors_2[1][7][11] = 0.741629992079;
   fEigenVectors_2[1][7][12] = -0.00784212314719;
   fEigenVectors_2[1][7][13] = 0.00916283370958;
   fEigenVectors_2[1][7][14] = 0.00240043788249;
   fEigenVectors_2[1][7][15] = -0.00838708879575;
   fEigenVectors_2[1][7][16] = -0.000435310937367;
   fEigenVectors_2[1][8][0] = 1.86316103765e-05;
   fEigenVectors_2[1][8][1] = 0.000174304960384;
   fEigenVectors_2[1][8][2] = 7.54392175313e-05;
   fEigenVectors_2[1][8][3] = -0.000321136123289;
   fEigenVectors_2[1][8][4] = 0.000820466440015;
   fEigenVectors_2[1][8][5] = 0.000385380233059;
   fEigenVectors_2[1][8][6] = -0.00971506005097;
   fEigenVectors_2[1][8][7] = -0.00291385781462;
   fEigenVectors_2[1][8][8] = -0.0324483736889;
   fEigenVectors_2[1][8][9] = -0.0107726248061;
   fEigenVectors_2[1][8][10] = 0.0170156190617;
   fEigenVectors_2[1][8][11] = -0.0122717554152;
   fEigenVectors_2[1][8][12] = -0.845384821737;
   fEigenVectors_2[1][8][13] = -0.523301972097;
   fEigenVectors_2[1][8][14] = 0.0367699735855;
   fEigenVectors_2[1][8][15] = -0.0660570517007;
   fEigenVectors_2[1][8][16] = 0.0636480657611;
   fEigenVectors_2[1][9][0] = 1.5264669198e-05;
   fEigenVectors_2[1][9][1] = -0.000249115854834;
   fEigenVectors_2[1][9][2] = 1.80219746434e-05;
   fEigenVectors_2[1][9][3] = -0.000545573877955;
   fEigenVectors_2[1][9][4] = -0.000242792897454;
   fEigenVectors_2[1][9][5] = 0.000994127800069;
   fEigenVectors_2[1][9][6] = -0.00922840348123;
   fEigenVectors_2[1][9][7] = 0.00220348630478;
   fEigenVectors_2[1][9][8] = 0.0110059065312;
   fEigenVectors_2[1][9][9] = 0.00701097478606;
   fEigenVectors_2[1][9][10] = -0.00381498248022;
   fEigenVectors_2[1][9][11] = 0.00188027300813;
   fEigenVectors_2[1][9][12] = 0.0218015739404;
   fEigenVectors_2[1][9][13] = 0.0899914463133;
   fEigenVectors_2[1][9][14] = 0.0334591916439;
   fEigenVectors_2[1][9][15] = -0.0214209725207;
   fEigenVectors_2[1][9][16] = 0.994770353319;
   fEigenVectors_2[1][10][0] = -0.00066713238192;
   fEigenVectors_2[1][10][1] = -0.000151565357538;
   fEigenVectors_2[1][10][2] = -0.000214561066473;
   fEigenVectors_2[1][10][3] = 0.0194146648118;
   fEigenVectors_2[1][10][4] = -0.114437212762;
   fEigenVectors_2[1][10][5] = 0.0668527732987;
   fEigenVectors_2[1][10][6] = 0.00487555373289;
   fEigenVectors_2[1][10][7] = 0.0027110218914;
   fEigenVectors_2[1][10][8] = -0.00795448441064;
   fEigenVectors_2[1][10][9] = 0.00337731537549;
   fEigenVectors_2[1][10][10] = -0.00391084616413;
   fEigenVectors_2[1][10][11] = -0.0311927971039;
   fEigenVectors_2[1][10][12] = 0.482851304819;
   fEigenVectors_2[1][10][13] = -0.809633916979;
   fEigenVectors_2[1][10][14] = -0.22959767244;
   fEigenVectors_2[1][10][15] = 0.184546238462;
   fEigenVectors_2[1][10][16] = 0.0744206576859;
   fEigenVectors_2[1][11][0] = 0.999999598224;
   fEigenVectors_2[1][11][1] = 0.000461143185776;
   fEigenVectors_2[1][11][2] = -0.000253338291877;
   fEigenVectors_2[1][11][3] = -0.000190804746488;
   fEigenVectors_2[1][11][4] = 9.11282096019e-05;
   fEigenVectors_2[1][11][5] = -2.04518846649e-05;
   fEigenVectors_2[1][11][6] = 3.79060732491e-05;
   fEigenVectors_2[1][11][7] = 1.24082389405e-05;
   fEigenVectors_2[1][11][8] = 4.41531023169e-05;
   fEigenVectors_2[1][11][9] = 9.87546947865e-06;
   fEigenVectors_2[1][11][10] = 4.0160951773e-05;
   fEigenVectors_2[1][11][11] = -2.68530377578e-05;
   fEigenVectors_2[1][11][12] = 0.000352793558009;
   fEigenVectors_2[1][11][13] = -0.000558666468664;
   fEigenVectors_2[1][11][14] = -0.000134422084117;
   fEigenVectors_2[1][11][15] = 0.000140527715305;
   fEigenVectors_2[1][11][16] = 3.50390185623e-05;
   fEigenVectors_2[1][12][0] = 9.20983616494e-05;
   fEigenVectors_2[1][12][1] = 0.0279384499591;
   fEigenVectors_2[1][12][2] = 0.00456212744325;
   fEigenVectors_2[1][12][3] = 0.439763539515;
   fEigenVectors_2[1][12][4] = 0.231050820464;
   fEigenVectors_2[1][12][5] = -0.0772778201957;
   fEigenVectors_2[1][12][6] = -0.401680792647;
   fEigenVectors_2[1][12][7] = -0.0383887433226;
   fEigenVectors_2[1][12][8] = -0.167054003351;
   fEigenVectors_2[1][12][9] = -0.0508161770757;
   fEigenVectors_2[1][12][10] = -0.459310032881;
   fEigenVectors_2[1][12][11] = 0.149249440716;
   fEigenVectors_2[1][12][12] = 0.0067367365462;
   fEigenVectors_2[1][12][13] = 0.00711610956441;
   fEigenVectors_2[1][12][14] = -0.425985420292;
   fEigenVectors_2[1][12][15] = -0.371931737343;
   fEigenVectors_2[1][12][16] = 0.00243084049306;
   fEigenVectors_2[1][13][0] = -5.41212931971e-07;
   fEigenVectors_2[1][13][1] = 0.0282782666957;
   fEigenVectors_2[1][13][2] = 0.00331567531029;
   fEigenVectors_2[1][13][3] = 0.409170025231;
   fEigenVectors_2[1][13][4] = 0.205363263137;
   fEigenVectors_2[1][13][5] = -0.0930648655576;
   fEigenVectors_2[1][13][6] = -0.186677119767;
   fEigenVectors_2[1][13][7] = 0.0473380541474;
   fEigenVectors_2[1][13][8] = 0.0839348222525;
   fEigenVectors_2[1][13][9] = 0.0774207214674;
   fEigenVectors_2[1][13][10] = 0.814018207691;
   fEigenVectors_2[1][13][11] = -0.154181370057;
   fEigenVectors_2[1][13][12] = 0.0401064544174;
   fEigenVectors_2[1][13][13] = -0.0206786585365;
   fEigenVectors_2[1][13][14] = -0.0859429370894;
   fEigenVectors_2[1][13][15] = -0.187045091261;
   fEigenVectors_2[1][13][16] = 0.000331496214489;
   fEigenVectors_2[1][14][0] = 3.19339511959e-05;
   fEigenVectors_2[1][14][1] = 0.0241969040625;
   fEigenVectors_2[1][14][2] = 0.003788692676;
   fEigenVectors_2[1][14][3] = 0.422030442021;
   fEigenVectors_2[1][14][4] = 0.218375205919;
   fEigenVectors_2[1][14][5] = -0.0812789755782;
   fEigenVectors_2[1][14][6] = -0.297546327472;
   fEigenVectors_2[1][14][7] = -0.016401900094;
   fEigenVectors_2[1][14][8] = -0.0741533346041;
   fEigenVectors_2[1][14][9] = -0.0153936667812;
   fEigenVectors_2[1][14][10] = -0.13915228358;
   fEigenVectors_2[1][14][11] = 0.0842247020062;
   fEigenVectors_2[1][14][12] = 0.0300512674387;
   fEigenVectors_2[1][14][13] = -0.0680197408226;
   fEigenVectors_2[1][14][14] = 0.60867635927;
   fEigenVectors_2[1][14][15] = 0.519566380829;
   fEigenVectors_2[1][14][16] = -0.00590594425605;
   fEigenVectors_2[1][15][0] = 2.21230393627e-06;
   fEigenVectors_2[1][15][1] = 0.0108045488226;
   fEigenVectors_2[1][15][2] = 0.0186933850833;
   fEigenVectors_2[1][15][3] = 0.0111477674469;
   fEigenVectors_2[1][15][4] = 0.247468174554;
   fEigenVectors_2[1][15][5] = 0.67750392628;
   fEigenVectors_2[1][15][6] = 0.00930962837056;
   fEigenVectors_2[1][15][7] = -0.637805061624;
   fEigenVectors_2[1][15][8] = 0.166281460091;
   fEigenVectors_2[1][15][9] = -0.152065321037;
   fEigenVectors_2[1][15][10] = 0.0691120860503;
   fEigenVectors_2[1][15][11] = 0.128893166681;
   fEigenVectors_2[1][15][12] = -0.00572050767203;
   fEigenVectors_2[1][15][13] = 0.00635474108039;
   fEigenVectors_2[1][15][14] = 0.00133614509907;
   fEigenVectors_2[1][15][15] = -0.00608888975614;
   fEigenVectors_2[1][15][16] = -0.000481151475607;
   fEigenVectors_2[1][16][0] = 1.0145692003e-05;
   fEigenVectors_2[1][16][1] = 0.00369756551458;
   fEigenVectors_2[1][16][2] = 0.000380911222505;
   fEigenVectors_2[1][16][3] = 0.0426103421853;
   fEigenVectors_2[1][16][4] = 0.0247765521797;
   fEigenVectors_2[1][16][5] = -0.00951490884411;
   fEigenVectors_2[1][16][6] = -0.0369153027417;
   fEigenVectors_2[1][16][7] = -5.50798172498e-05;
   fEigenVectors_2[1][16][8] = -0.00248297519278;
   fEigenVectors_2[1][16][9] = 0.00483154701746;
   fEigenVectors_2[1][16][10] = 0.0761581479724;
   fEigenVectors_2[1][16][11] = -0.0104951747765;
   fEigenVectors_2[1][16][12] = -0.21075650494;
   fEigenVectors_2[1][16][13] = 0.212315577157;
   fEigenVectors_2[1][16][14] = -0.618802717893;
   fEigenVectors_2[1][16][15] = 0.719221164722;
   fEigenVectors_2[1][16][16] = 0.021715675698;
   fEigenVectors_2[2][0][0] = -0.000246825557912;
   fEigenVectors_2[2][0][1] = 0.998432503484;
   fEigenVectors_2[2][0][2] = -0.0312719756262;
   fEigenVectors_2[2][0][3] = -0.0319382671129;
   fEigenVectors_2[2][0][4] = 0.0220651120479;
   fEigenVectors_2[2][0][5] = -0.00876388718178;
   fEigenVectors_2[2][0][6] = 0.00852357233942;
   fEigenVectors_2[2][0][7] = 0.00158483714691;
   fEigenVectors_2[2][0][8] = -0.0201684663176;
   fEigenVectors_2[2][0][9] = -0.00170832060457;
   fEigenVectors_2[2][0][10] = -0.00774842400569;
   fEigenVectors_2[2][0][11] = 0.000184894480701;
   fEigenVectors_2[2][0][12] = -0.00494199817111;
   fEigenVectors_2[2][0][13] = 0.000868545428733;
   fEigenVectors_2[2][0][14] = 0.000379831101465;
   fEigenVectors_2[2][0][15] = 0.000140369502009;
   fEigenVectors_2[2][0][16] = -0.000740587620209;
   fEigenVectors_2[2][1][0] = 0.00012442552269;
   fEigenVectors_2[2][1][1] = 0.0307572042179;
   fEigenVectors_2[2][1][2] = 0.999308256669;
   fEigenVectors_2[2][1][3] = -0.00515142999474;
   fEigenVectors_2[2][1][4] = 0.0150293036507;
   fEigenVectors_2[2][1][5] = 0.00724016650221;
   fEigenVectors_2[2][1][6] = -0.00336280665835;
   fEigenVectors_2[2][1][7] = -0.00524623078084;
   fEigenVectors_2[2][1][8] = -0.00409808173011;
   fEigenVectors_2[2][1][9] = 0.00061999005606;
   fEigenVectors_2[2][1][10] = -0.00837341613847;
   fEigenVectors_2[2][1][11] = -0.00244330994705;
   fEigenVectors_2[2][1][12] = 0.000118567173754;
   fEigenVectors_2[2][1][13] = 0.000114954980303;
   fEigenVectors_2[2][1][14] = 3.26927478193e-05;
   fEigenVectors_2[2][1][15] = 0.000100366217691;
   fEigenVectors_2[2][1][16] = -0.000132309090895;
   fEigenVectors_2[2][2][0] = -2.62759405629e-06;
   fEigenVectors_2[2][2][1] = -0.000296494367661;
   fEigenVectors_2[2][2][2] = 0.000100957879418;
   fEigenVectors_2[2][2][3] = -0.238194657381;
   fEigenVectors_2[2][2][4] = 0.0765010511183;
   fEigenVectors_2[2][2][5] = -0.0941697944467;
   fEigenVectors_2[2][2][6] = 0.0891787537191;
   fEigenVectors_2[2][2][7] = -0.00613156565404;
   fEigenVectors_2[2][2][8] = 0.325001239143;
   fEigenVectors_2[2][2][9] = 0.267795094477;
   fEigenVectors_2[2][2][10] = 0.270850132042;
   fEigenVectors_2[2][2][11] = -0.767986970065;
   fEigenVectors_2[2][2][12] = 0.274337650569;
   fEigenVectors_2[2][2][13] = -0.00887386747769;
   fEigenVectors_2[2][2][14] = 0.0621638012843;
   fEigenVectors_2[2][2][15] = 0.0142816397699;
   fEigenVectors_2[2][2][16] = -0.0253062464884;
   fEigenVectors_2[2][3][0] = 3.47376922816e-05;
   fEigenVectors_2[2][3][1] = -0.00033512556988;
   fEigenVectors_2[2][3][2] = -8.68353132362e-05;
   fEigenVectors_2[2][3][3] = -0.287077732401;
   fEigenVectors_2[2][3][4] = 0.10250455666;
   fEigenVectors_2[2][3][5] = -0.129355899546;
   fEigenVectors_2[2][3][6] = 0.138808719058;
   fEigenVectors_2[2][3][7] = -0.0195847729931;
   fEigenVectors_2[2][3][8] = 0.792706146541;
   fEigenVectors_2[2][3][9] = 0.100894529149;
   fEigenVectors_2[2][3][10] = -0.29541739107;
   fEigenVectors_2[2][3][11] = 0.370561992833;
   fEigenVectors_2[2][3][12] = -0.0785253947353;
   fEigenVectors_2[2][3][13] = 0.0293703965434;
   fEigenVectors_2[2][3][14] = 0.0103378592956;
   fEigenVectors_2[2][3][15] = 0.0199873100693;
   fEigenVectors_2[2][3][16] = 0.00301825022374;
   fEigenVectors_2[2][4][0] = -0.000171699243628;
   fEigenVectors_2[2][4][1] = -2.69294862228e-05;
   fEigenVectors_2[2][4][2] = -0.000726065771508;
   fEigenVectors_2[2][4][3] = 0.592504283734;
   fEigenVectors_2[2][4][4] = 0.376572941777;
   fEigenVectors_2[2][4][5] = -0.438901272349;
   fEigenVectors_2[2][4][6] = 0.406449000794;
   fEigenVectors_2[2][4][7] = 0.0909641264198;
   fEigenVectors_2[2][4][8] = -0.0526654945485;
   fEigenVectors_2[2][4][9] = 0.140759866266;
   fEigenVectors_2[2][4][10] = -0.30361901404;
   fEigenVectors_2[2][4][11] = -0.116376649277;
   fEigenVectors_2[2][4][12] = 0.0173187925372;
   fEigenVectors_2[2][4][13] = 0.084365195941;
   fEigenVectors_2[2][4][14] = 0.0635360427856;
   fEigenVectors_2[2][4][15] = -0.0349992145691;
   fEigenVectors_2[2][4][16] = -0.00520782339501;
   fEigenVectors_2[2][5][0] = 2.31029549816e-06;
   fEigenVectors_2[2][5][1] = -0.000145740267002;
   fEigenVectors_2[2][5][2] = -0.000491909395853;
   fEigenVectors_2[2][5][3] = -0.00650548650417;
   fEigenVectors_2[2][5][4] = -0.0805005243631;
   fEigenVectors_2[2][5][5] = -0.11277488096;
   fEigenVectors_2[2][5][6] = 0.106997812447;
   fEigenVectors_2[2][5][7] = -0.740052065764;
   fEigenVectors_2[2][5][8] = -0.153643000043;
   fEigenVectors_2[2][5][9] = 0.566684905269;
   fEigenVectors_2[2][5][10] = 0.179406063175;
   fEigenVectors_2[2][5][11] = 0.207773706443;
   fEigenVectors_2[2][5][12] = -0.0390950548097;
   fEigenVectors_2[2][5][13] = 0.00130155772531;
   fEigenVectors_2[2][5][14] = -0.00242195684803;
   fEigenVectors_2[2][5][15] = -0.000651611007755;
   fEigenVectors_2[2][5][16] = 0.00158289837353;
   fEigenVectors_2[2][6][0] = 2.01472815699e-06;
   fEigenVectors_2[2][6][1] = 9.76223597919e-05;
   fEigenVectors_2[2][6][2] = -0.000463030338272;
   fEigenVectors_2[2][6][3] = -0.00845086263891;
   fEigenVectors_2[2][6][4] = -0.126265535879;
   fEigenVectors_2[2][6][5] = -0.176591230605;
   fEigenVectors_2[2][6][6] = 0.153764629073;
   fEigenVectors_2[2][6][7] = -0.593928577629;
   fEigenVectors_2[2][6][8] = 0.0829851623734;
   fEigenVectors_2[2][6][9] = -0.706534450101;
   fEigenVectors_2[2][6][10] = -0.147509531699;
   fEigenVectors_2[2][6][11] = -0.218357104084;
   fEigenVectors_2[2][6][12] = 0.0294745522763;
   fEigenVectors_2[2][6][13] = -0.00434794441863;
   fEigenVectors_2[2][6][14] = 0.00029157351705;
   fEigenVectors_2[2][6][15] = -0.000959110340182;
   fEigenVectors_2[2][6][16] = -0.00108732355681;
   fEigenVectors_2[2][7][0] = -7.61076901903e-05;
   fEigenVectors_2[2][7][1] = -0.000555767072817;
   fEigenVectors_2[2][7][2] = -0.000217322001906;
   fEigenVectors_2[2][7][3] = 0.119566673276;
   fEigenVectors_2[2][7][4] = 0.543402456284;
   fEigenVectors_2[2][7][5] = 0.0315695749097;
   fEigenVectors_2[2][7][6] = 0.087440369933;
   fEigenVectors_2[2][7][7] = -0.0399749103956;
   fEigenVectors_2[2][7][8] = 0.15024381838;
   fEigenVectors_2[2][7][9] = -0.263962053689;
   fEigenVectors_2[2][7][10] = 0.726907500761;
   fEigenVectors_2[2][7][11] = 0.242380648724;
   fEigenVectors_2[2][7][12] = -0.0267014241585;
   fEigenVectors_2[2][7][13] = 0.00502938035319;
   fEigenVectors_2[2][7][14] = 0.00604148966132;
   fEigenVectors_2[2][7][15] = -0.00315325356207;
   fEigenVectors_2[2][7][16] = 4.26720529443e-05;
   fEigenVectors_2[2][8][0] = -2.06835200865e-05;
   fEigenVectors_2[2][8][1] = -5.78924405979e-05;
   fEigenVectors_2[2][8][2] = 2.76200517244e-05;
   fEigenVectors_2[2][8][3] = -0.00339418680681;
   fEigenVectors_2[2][8][4] = 0.0459189135961;
   fEigenVectors_2[2][8][5] = -0.282291923837;
   fEigenVectors_2[2][8][6] = -0.397420474657;
   fEigenVectors_2[2][8][7] = -0.0243104914342;
   fEigenVectors_2[2][8][8] = 0.0147908456133;
   fEigenVectors_2[2][8][9] = -0.00425775412105;
   fEigenVectors_2[2][8][10] = 0.0284216600275;
   fEigenVectors_2[2][8][11] = -0.0253825280457;
   fEigenVectors_2[2][8][12] = 0.0180698509232;
   fEigenVectors_2[2][8][13] = 0.747960713534;
   fEigenVectors_2[2][8][14] = -0.422762390247;
   fEigenVectors_2[2][8][15] = 0.138212602365;
   fEigenVectors_2[2][8][16] = 0.0191230948835;
   fEigenVectors_2[2][9][0] = -1.18326993104e-05;
   fEigenVectors_2[2][9][1] = -0.000158736507481;
   fEigenVectors_2[2][9][2] = 5.65199673764e-05;
   fEigenVectors_2[2][9][3] = -0.0031062439335;
   fEigenVectors_2[2][9][4] = 0.0477670507207;
   fEigenVectors_2[2][9][5] = -0.286581810485;
   fEigenVectors_2[2][9][6] = -0.397623372059;
   fEigenVectors_2[2][9][7] = -0.0229666774371;
   fEigenVectors_2[2][9][8] = 0.0209924066961;
   fEigenVectors_2[2][9][9] = -0.00903219788501;
   fEigenVectors_2[2][9][10] = 0.00275739188118;
   fEigenVectors_2[2][9][11] = 0.0304983070745;
   fEigenVectors_2[2][9][12] = 0.00599716548684;
   fEigenVectors_2[2][9][13] = -0.0886528932584;
   fEigenVectors_2[2][9][14] = 0.19903361318;
   fEigenVectors_2[2][9][15] = -0.573131300625;
   fEigenVectors_2[2][9][16] = -0.616034498312;
   fEigenVectors_2[2][10][0] = 0.0007635309206;
   fEigenVectors_2[2][10][1] = -0.000121084344824;
   fEigenVectors_2[2][10][2] = -4.83935585363e-05;
   fEigenVectors_2[2][10][3] = 0.0411278610475;
   fEigenVectors_2[2][10][4] = 0.108496157464;
   fEigenVectors_2[2][10][5] = -0.34554713395;
   fEigenVectors_2[2][10][6] = -0.314534669164;
   fEigenVectors_2[2][10][7] = -0.00535720389821;
   fEigenVectors_2[2][10][8] = 0.0189570269629;
   fEigenVectors_2[2][10][9] = 0.0150208487743;
   fEigenVectors_2[2][10][10] = -0.0217785274398;
   fEigenVectors_2[2][10][11] = 0.000614256640878;
   fEigenVectors_2[2][10][12] = 0.0614891713122;
   fEigenVectors_2[2][10][13] = -0.648517010556;
   fEigenVectors_2[2][10][14] = -0.516861439455;
   fEigenVectors_2[2][10][15] = 0.270846112663;
   fEigenVectors_2[2][10][16] = 0.0474829602009;
   fEigenVectors_2[2][11][0] = -0.999999636952;
   fEigenVectors_2[2][11][1] = -0.000239611290729;
   fEigenVectors_2[2][11][2] = 0.000132478010299;
   fEigenVectors_2[2][11][3] = -4.3005221916e-05;
   fEigenVectors_2[2][11][4] = -4.62140045989e-05;
   fEigenVectors_2[2][11][5] = -0.000159137311355;
   fEigenVectors_2[2][11][6] = -0.00030592781906;
   fEigenVectors_2[2][11][7] = -2.60558746479e-05;
   fEigenVectors_2[2][11][8] = 5.96952256081e-05;
   fEigenVectors_2[2][11][9] = 8.27655455889e-06;
   fEigenVectors_2[2][11][10] = -3.42971284169e-05;
   fEigenVectors_2[2][11][11] = 5.73771620508e-05;
   fEigenVectors_2[2][11][12] = 0.000197851520008;
   fEigenVectors_2[2][11][13] = -0.000520587455302;
   fEigenVectors_2[2][11][14] = -0.000412056352438;
   fEigenVectors_2[2][11][15] = 0.000189298108081;
   fEigenVectors_2[2][11][16] = 6.05789871404e-05;
   fEigenVectors_2[2][12][0] = -2.82689206157e-05;
   fEigenVectors_2[2][12][1] = 0.0269842343834;
   fEigenVectors_2[2][12][2] = 0.00426106100036;
   fEigenVectors_2[2][12][3] = 0.425263481767;
   fEigenVectors_2[2][12][4] = -0.208825902987;
   fEigenVectors_2[2][12][5] = 0.163019353509;
   fEigenVectors_2[2][12][6] = -0.170938849201;
   fEigenVectors_2[2][12][7] = -0.0564698397714;
   fEigenVectors_2[2][12][8] = 0.325480995113;
   fEigenVectors_2[2][12][9] = 0.0608443149976;
   fEigenVectors_2[2][12][10] = 0.0999115455212;
   fEigenVectors_2[2][12][11] = -0.196262280528;
   fEigenVectors_2[2][12][12] = -0.460803403295;
   fEigenVectors_2[2][12][13] = -0.0547208998419;
   fEigenVectors_2[2][12][14] = -0.180877335764;
   fEigenVectors_2[2][12][15] = -0.424820182516;
   fEigenVectors_2[2][12][16] = 0.359371819173;
   fEigenVectors_2[2][13][0] = 0.000163769060697;
   fEigenVectors_2[2][13][1] = 0.0281169807734;
   fEigenVectors_2[2][13][2] = 0.0031951482206;
   fEigenVectors_2[2][13][3] = 0.392797133479;
   fEigenVectors_2[2][13][4] = -0.187879576307;
   fEigenVectors_2[2][13][5] = 0.169475468761;
   fEigenVectors_2[2][13][6] = -0.162425598813;
   fEigenVectors_2[2][13][7] = -0.0622000754824;
   fEigenVectors_2[2][13][8] = 0.211611184367;
   fEigenVectors_2[2][13][9] = 0.000289851569216;
   fEigenVectors_2[2][13][10] = 0.00448928009664;
   fEigenVectors_2[2][13][11] = 0.195554731296;
   fEigenVectors_2[2][13][12] = 0.802012886688;
   fEigenVectors_2[2][13][13] = 0.00693509100805;
   fEigenVectors_2[2][13][14] = 0.0406407355965;
   fEigenVectors_2[2][13][15] = -0.0828759927077;
   fEigenVectors_2[2][13][16] = 0.125713833356;
   fEigenVectors_2[2][14][0] = -3.80357235852e-05;
   fEigenVectors_2[2][14][1] = 0.0233855903384;
   fEigenVectors_2[2][14][2] = 0.0034728017877;
   fEigenVectors_2[2][14][3] = 0.394023136371;
   fEigenVectors_2[2][14][4] = -0.18910379427;
   fEigenVectors_2[2][14][5] = 0.150065719932;
   fEigenVectors_2[2][14][6] = -0.160024203152;
   fEigenVectors_2[2][14][7] = -0.0520246796573;
   fEigenVectors_2[2][14][8] = 0.237202892553;
   fEigenVectors_2[2][14][9] = 0.0293068751329;
   fEigenVectors_2[2][14][10] = 0.0667350894972;
   fEigenVectors_2[2][14][11] = -0.078887253749;
   fEigenVectors_2[2][14][12] = -0.225796382205;
   fEigenVectors_2[2][14][13] = 0.00967698854918;
   fEigenVectors_2[2][14][14] = 0.230699242946;
   fEigenVectors_2[2][14][15] = 0.604712372127;
   fEigenVectors_2[2][14][16] = -0.468844134028;
   fEigenVectors_2[2][15][0] = 2.2431104537e-06;
   fEigenVectors_2[2][15][1] = 0.0104749578652;
   fEigenVectors_2[2][15][2] = 0.019064204481;
   fEigenVectors_2[2][15][3] = 0.00772729061182;
   fEigenVectors_2[2][15][4] = -0.622064314104;
   fEigenVectors_2[2][15][5] = -0.51564240349;
   fEigenVectors_2[2][15][6] = 0.300960293538;
   fEigenVectors_2[2][15][7] = 0.27929910394;
   fEigenVectors_2[2][15][8] = 0.0293625065614;
   fEigenVectors_2[2][15][9] = -0.0556900325805;
   fEigenVectors_2[2][15][10] = 0.385937718985;
   fEigenVectors_2[2][15][11] = 0.158166504196;
   fEigenVectors_2[2][15][12] = -0.00749996845667;
   fEigenVectors_2[2][15][13] = 0.00506892715236;
   fEigenVectors_2[2][15][14] = 0.00358116546349;
   fEigenVectors_2[2][15][15] = -0.00261773810594;
   fEigenVectors_2[2][15][16] = 0.00110003602729;
   fEigenVectors_2[2][16][0] = 2.40113044463e-05;
   fEigenVectors_2[2][16][1] = 0.00325039540062;
   fEigenVectors_2[2][16][2] = 0.000359834103268;
   fEigenVectors_2[2][16][3] = 0.0465467991724;
   fEigenVectors_2[2][16][4] = -0.07495345913;
   fEigenVectors_2[2][16][5] = 0.334382280824;
   fEigenVectors_2[2][16][6] = 0.421888714595;
   fEigenVectors_2[2][16][7] = 0.0181302860754;
   fEigenVectors_2[2][16][8] = 0.0294052261839;
   fEigenVectors_2[2][16][9] = 0.0174080286177;
   fEigenVectors_2[2][16][10] = -0.00450954386699;
   fEigenVectors_2[2][16][11] = -0.0125299780701;
   fEigenVectors_2[2][16][12] = 0.0662567264752;
   fEigenVectors_2[2][16][13] = 0.0292152033697;
   fEigenVectors_2[2][16][14] = -0.647192232123;
   fEigenVectors_2[2][16][15] = -0.155550290655;
   fEigenVectors_2[2][16][16] = -0.502426284684;
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_(n-2)2_no_ev::Transform_2( std::vector<double>& iv, int cls ) const
{
   // PCA transformation
   const int nVar = 17;
   double *dv = new double[nVar];
   double *rv = new double[nVar];
   if (cls < 0 || cls > 2) {
       if (2 > 1 ) cls = 2;
       else cls = 2;
   }

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
      indicesGet.push_back( 15);
      indicesGet.push_back( 16);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
      indicesPut.push_back( 15);
      indicesPut.push_back( 16);
   } 

   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];

   // Perform PCA and put it into PCAed events tree
   this->X2P_2( dv, rv, cls );
   for (int ivar=0; ivar<nVar; ivar++) iv[indicesPut.at(ivar)] = rv[ivar];

   delete [] dv;
   delete [] rv;
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_(n-2)2_no_ev::InitTransform()
{
   InitTransform_1();
   InitTransform_2();
}

//_______________________________________________________________________
inline void ReadkMLP_pca_ce_600_(n-2)2_no_ev::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
   Transform_2( iv, sigOrBgd );
}
